### ISSUE TITLE
win11执行复制并传到远端的快捷键，一直在上传，导致机器卡顿

### ISSUE THREAD

**Issue by YLShiJustFly** [Jeric-X/SyncClipboard#103]
### 错误描述 | Describe the bug

win11执行复制并传到远端的快捷键，一直在上传，导致机器卡顿

### 复现步骤 | Steps to Reproduce

win11纯净版系统，执行传远端的快捷键

### 截图 | Screenshots

[

https://github.com/Jeric-X/SyncClipboard/assets/57145262/6c1ebcfd-4760-4a88-b311-46230935dbeb

](url)

### 服务端信息 | Server

docker 

### 桌面端信息 | Desktop

win11

**Comment by YLShiJustFly** [comment]
log当成附件发了
[20240710.txt](https://github.com/user-attachments/files/16193465/20240710.txt)

**Comment by Jeric-X** [comment]
问几个详细情况
1、使用快捷键时，剪贴板自动同步的开关是开着还是关着的
2、这个问题是百分百或者很容易复现的吗

**Comment by YLShiJustFly** [comment]
> 问几个详细情况 1、使用快捷键时，剪贴板自动同步的开关是开着还是关着的 2、这个问题是百分百或者很容易复现的吗

1. 开关开着的
2. 必现的

**Comment by Jeric-X** [comment]
你真不是快捷键设置成了单个按键，然后按住了没松手？我实在找不到无限发送通知的理由了

**Comment by YLShiJustFly** [comment]
> 你真不是快捷键设置成了单个按键，然后按住了没松手？我实在找不到无限发送通知的理由了

设置了control+c，换成control+shift+c也是一样的。周末我把所有设置都截图发到这里。

**Comment by Jeric-X** [comment]
好吧，ctrl+c的话是会无限重复，因为原理是模拟按ctrl+c后上传一次，这点会增加限制不让设置。
其他快捷键有问题的话还得继续定位问题

------------------ 原始邮件 ------------------
发件人: YLShi ***@***.***&gt;
发送时间: 2024年7月19日 10:05
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] win11执行复制并传到远端的快捷键，一直在上传，导致机器卡顿 (Issue #103)





  
你真不是快捷键设置成了单个按键，然后按住了没松手？我实在找不到无限发送通知的理由了
  
设置了control+c，换成control+shift+c也是一样的。周末我把所有设置都截图发到这里。

**Comment by Jeric-X** [comment]
v2.8.4 已禁止快捷键设置为ctrl + c，如果设置为其他快捷键仍有问题可以重新打开issue
