### ISSUE TITLE
能否复制文字图片到剪切板的是时候上传，剪切图片视频的时候不上传

### ISSUE THREAD

**Issue by lyscop** [Jeric-X/SyncClipboard#107]
### 描述你想添加的功能 | Describe the feature you'd like

剪切图片视频到另一个文件粘贴，还没上传完，粘贴的时候弹窗正在上传，想剪切的时候不上传图片视频文件
![2tnjfks1 5rf](https://github.com/user-attachments/assets/8ec0aade-36d3-4c16-9d4c-2972d4d16fc6)

### 描述你正在使用的替代方案 | Describe alternatives you are using

等上传完点继续粘贴

**Comment by Jeric-X** [comment]
2.8.4增加了支持
![dkfafwm0 oww](https://github.com/user-attachments/assets/e75ab318-0098-497c-bd6b-e60f1ca3288b)
