### ISSUE TITLE
截图后剪切板被替换为SyncClipboard文件夹临时图片的路径

### ISSUE THREAD

**Issue by lyscop** [Jeric-X/SyncClipboard#110]
### 描述你想添加的功能 | Describe the feature you'd like

截图后剪切板被替换
`file:///C:/Users/Administrator/AppData/Roaming/SyncClipboard/file/20240807/temp images/d04owi01.5qh.png`

![fco51dqb l30](https://github.com/user-attachments/assets/c3e579e4-6c75-437c-aacc-78b6ea529822)

复制多个文件会一直生成临时压缩包
![fraxumcn q4i](https://github.com/user-attachments/assets/2cdb6de5-754b-4e97-aae2-6ea234cba690)

### 描述你正在使用的替代方案 | Describe alternatives you are using

要再在剪切板重新复制图片替换当前剪切板路径

**Comment by Jeric-X** [comment]
1. 关闭图片轻松拷贝。原理：你的历史记录工具在剪贴板内同时有文件和图片的情况时优先展示文件
2. 拷贝多个文件的原理是这样的，因为网络传输的是一个压缩文件。如果你不希望这样，可以提一个新需求：提供关闭同步多个文件的开关


------------------ 原始邮件 ------------------
发件人: lyscop ***@***.***&gt;
发送时间: 2024年8月7日 10:44
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] 截图后剪切板被替换为SyncClipboard文件夹临时图片的路径 (Issue #110)





 
描述你想添加的功能 | Describe the feature you'd like
 
截图后，剪切板变成图片路径
 file://localhost/C:/Users/Administrator/AppData/Roaming/SyncClipboard/file/20240807/temp images/d04owi01.5qh.png
 
fco51dqb.l30.png (view on web)
 
描述你正在使用的替代方案 | Describe alternatives you are using
 
要再在剪切板重新复制图片替换当前剪切板路径

**Comment by lyscop** [comment]
改好了
