### ISSUE TITLE
Windows端使用Webdav同步，能下载成功但上传失败

### ISSUE THREAD

**Issue by axutongxue** [Jeric-X/SyncClipboard#117]
### 错误描述 | Describe the bug

未开启剪贴板同步，仅使用快捷键在需要的时候上传下载

无[之前issue](https://github.com/Jeric-X/SyncClipboard/issues/33)中末尾`/`的问题

但问题和之前一样，iOS端使用快捷指令能上传成功，Windows端使用快捷键能下载成功，但Windows端无法上传成功

![20240820101318](https://github.com/user-attachments/assets/65db0038-2786-426c-8cde-30a5e442f349)

且更换不同的webdav服务之后问题依旧，可能排除Webdav服务限制的问题？

![20240820102345](https://github.com/user-attachments/assets/ebf7301f-4e2a-4353-a350-c83d8d6e8cef)

### 复现步骤 | Steps to Reproduce

未知

### 截图 | Screenshots

可以下载成功

![20240820103655](https://github.com/user-attachments/assets/f100843a-9f6e-4662-8651-3ccaa345f736)

### 服务端信息 | Server

坚果云/woelkli

### 桌面端信息 | Desktop

windows 10 22H2 19045

### 移动端信息 | Smartphone

iOS 16.6

**Comment by axutongxue** [comment]
OK，研究了一上午之后终于发现问题所在

尝试降级软件版本后发现问题依旧，于是进一步尝试清空软件配置后重试，结果发现问题就解决了。然后幸好有意识的备份了一下之前有问题的配置文件，对比之后发现问题大概率出现在重试次数这里

![20240820105636](https://github.com/user-attachments/assets/1e605955-5df3-489a-bb66-d0deed1d67cc)

后续测试果然是，只要重试次数设置为0，就会导致上传失败

![20240820110017](https://github.com/user-attachments/assets/adbc008f-2a86-4992-9a34-599642f0b7dc)

之所以会设置为0，是因为之前尝试用 Webdav 服务器同步剪贴板时，发现极易因为频繁读写被 Webdav 服务限制，所以尝试修改过轮询服务器间隔、重试次数、超时时间这些参数，没想到就算不开启「剪贴板同步」这个功能这些设置依旧生效

**Comment by Jeric-X** [comment]
是的，手动操作失败也会重试。看起来我的边界设置的有点问题，作为"重试次数"应该只影响失败重试，不该影响不需要重试的情况


------------------ 原始邮件 ------------------
发件人: 阿虚同学 ***@***.***&gt;
发送时间: 2024年8月20日 11:05
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] Windows端使用Webdav同步，能下载成功但上传失败 (Issue #117)





 
OK，研究了一上午之后终于发现问题所在
 
尝试降级软件版本后发现问题依旧，于是进一步尝试清空软件配置后重试，结果发现问题就解决了。然后幸好有意识的备份了一下之前有问题的配置文件，对比之后发现问题大概率出现在重试次数这里
 
20240820105636.jpg (view on web)
 
后续测试果然是，只要重试次数设置为0，就会导致上传失败
 
20240820110017_.jpg (view on web)
 
之所以会设置为0，是因为之前尝试用 Webdav 服务器同步剪贴板时，发现极易因为频繁读写被 Webdav 服务限制，所以尝试修改过轮询服务器间隔、重试次数、超时时间这些参数，没想到就算不开启「剪贴板同步」这个功能这些设置依旧生效
