### ISSUE TITLE
增加手动快捷键上传下载不限制文件大小的功能

### ISSUE THREAD

**Issue by xuzmbest** [Jeric-X/SyncClipboard#122]
### 描述你想添加的功能 | Describe the feature you'd like

增加手动快捷键上传下载不限制文件大小的功能。

### 描述你正在使用的替代方案 | Describe alternatives you are using

替代方案我现在只能是调整大小限制，但这里的限制应该是在自动默认情况下控制自动上传文件体积的情况，反而很实用。所以，应该增加一个专门手动上传大文件的功能。

**Comment by baifengs** [comment]
新功能已经在用了，非常棒。
