### ISSUE TITLE
Windows 10 LTSC 2016打不开SyncClipboard.exe 

### ISSUE THREAD

**Issue by gaojiannote** [Jeric-X/SyncClipboard#127]
### 错误描述 | Describe the bug

Windows 10 LTSC 2016打不开SyncClipboard.exe ,前两次打开提示安装依赖库，依赖库安装完成后再打开SyncClipboard.exe，没有任何反应，后台也看不到进程。

### 复现步骤 | Steps to Reproduce

Windows 10 LTSC 2016打不开SyncClipboard.exe ,前两次打开提示安装依赖库，依赖库安装完成后再打开SyncClipboard.exe，没有任何反应，后台也看不到进程。

### 服务端信息 | Server

N/A

### 桌面端信息 | Desktop

Windows 10 LTSC 2016

**Comment by Jeric-X** [comment]
传一下log(路径%AppData%\SyncClipboard\log)，你也可以先看看是不是和这个问题一样https://github.com/Jeric-X/SyncClipboard/issues/128

**Comment by gaojiannote** [comment]
> 传一下log(路径：%AppData%\SyncClipboard\log)，你也可以先看看是不是和这个问题一样#128

你好，没有产生改文件以及对应的文件夹。看了日志，有下面报错：
 Application: SyncClipboard.exe CoreCLR Version: 6.0.3324.36610 .NET Version: 6.0.33 Description: The process was terminated due to an unhandled exception. Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Microsoft.WindowsAppRuntime.dll' or one of its dependencies: 找不到指定的程序。 (0x8007007F) at Microsoft.Windows.Foundation.UndockedRegFreeWinRTCS.NativeMethods.WindowsAppRuntime_EnsureIsLoaded() at Microsoft.Windows.Foundation.UndockedRegFreeWinRTCS.AutoInitialize.AccessWindowsAppSDK() in C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.5.240428000\include\UndockedRegFreeWinRT-AutoInitializer.cs:line 33 at .cctor() --- End of inner exception stack trace ---  

win 10在打开SyncClipboard.exe时，以及按照提示安装了两个依赖包。

**Comment by Jeric-X** [comment]
win10版本太低


------------------ 原始邮件 ------------------
发件人: gaojiannote ***@***.***&gt;
发送时间: 2024年9月19日 08:01
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] Windows 10 LTSC 2016打不开SyncClipboard.exe  (Issue #127)

**Comment by gaojiannote** [comment]
> win10版本太低
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: gaojiannote ***@***.***&gt; 发送时间: 2024年9月19日 08:01 收件人: Jeric-X/SyncClipboard ***@***.***&gt; 抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [Jeric-X/SyncClipboard] Windows 10 LTSC 2016打不开SyncClipboard.exe (Issue #127)

好吧，谢谢您的回复。
