### ISSUE TITLE
突然无法正常启动程序

### ISSUE THREAD

**Issue by Gokou-Ruri** [Jeric-X/SyncClipboard#128]
### 错误描述 | Describe the bug

启动程序以后任务管理器里能看到两个`SyncClipboard.exe`进程，但几秒后就会消失。

### 复现步骤 | Steps to Reproduce

原本能运行的，手动从托盘图标退出后就无法再次运行了。即使重新下载覆盖文件，也仍然无法运行。重启电脑后依旧无法正常启动。原本的版本是2.8.5，重新下载过2.8.5和2.8.4均无法正常启动。
期间尝试过删除数据目录`C:\Users\ABC\AppData\Roaming\SyncClipboard`，仍旧无法正常启动。

### 服务端信息 | Server

-

### 桌面端信息 | Desktop

Windows 11 23h2 | Synclipboard Version: 2.8.4/2.8.5

### 其他附加信息 | Additional context

[log.zip](https://github.com/user-attachments/files/17012130/log.zip)

**Comment by Jeric-X** [comment]
创建快捷方式失败，检查是否有杀毒软件拦截
详细路径：
"C:\\Users\\ddjia\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\SyncClipboard.lnk"
windows通知依赖这个，之后考虑直接忽略这个问题，即使没有通知功能也先保证启动成功

**Comment by Gokou-Ruri** [comment]
> 创建快捷方式失败，检查是否有杀毒软件拦截 详细路径： "C:\Users\ddjia\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\SyncClipboard.lnk" windows通知依赖这个，之后考虑直接忽略这个问题，即使没有通知功能也先保证启动成功

感谢解答！经过排查发现这个快捷方式被安全软件拦截了。
许多用户可能不太了解Windows这个特性，可以增加一个“创建开始菜单快捷方式失败可能会导致Windows原生通知特性丢失”的提示吗？

**Comment by Gokou-Ruri** [comment]
> 主要是通知系统没了，提示系统就直接没了，暂时还没有非windows原生通知的功能，我考虑考虑这个提示放在哪

不好意思，我之前的表达有误，我的意思是可以增加一个小弹窗，在屏幕中间位置弹出，这样就不用额外写一个通知功能了。
