### ISSUE TITLE
软件开启后导致wps和office软件复制粘贴功能异常

### ISSUE THREAD

**Issue by vvwan04** [Jeric-X/SyncClipboard#130]
### 错误描述 | Describe the bug

软件开启后，在wps和office的excel中复制表格后，仅能将复制的内容粘贴为纯文字，而不能再进行选择粘贴。
<img width="642" alt="yh21rvol 3i5" src="https://github.com/user-attachments/assets/84688e74-c7da-4483-bd7e-54890856afc4">
但是关闭软件后，excel的复制粘贴功能就可以恢复正常。

### 复现步骤 | Steps to Reproduce

软件开启后，在wps和office的excel中复制表格后，仅能将复制的内容粘贴为纯文字，而不能再进行选择粘贴。但是关闭软件后，excel的复制粘贴功能就可以恢复正常。

### 服务端信息 | Server

Nextcloud

### 桌面端信息 | Desktop

macOS 14.5，Windows 10 22H2

**Comment by Jeric-X** [comment]
macos我没有测试过，win10也是这样吗?

**Comment by vvwan04** [comment]
> macos我没有测试过，windows我测试过没有这个问题，你在windows上也有这个问题吗？

是的，两个系统我都有测试过。

**Comment by Jeric-X** [comment]
我确认下，不管是哪个系统，你都指的是同一台电脑上的复制粘贴，而不是一台电脑复制同步到另一台电脑上粘贴

**Comment by vvwan04** [comment]
是的，在本电脑粘贴时，粘贴选项只有仅文本粘贴。

**Comment by Jeric-X** [comment]
新版本尝试修复了部分场景的问题，如果还有问题的话请重新打开issue并提供系统、表格软件的具体版本和操作细节
