### ISSUE TITLE
ios快捷指令 自动同步命令运行过程中运行其他快捷指令会中断

### ISSUE THREAD

**Issue by pkr5277** [Jeric-X/SyncClipboard#133]
### 错误描述 | Describe the bug

ios快捷指令 自动同步命令运行过程中运行其他快捷指令会导致自动同步中断，好像只能同时运行一个快捷指令

### 复现步骤 | Steps to Reproduce

自动同步命令运行过程中运行其他快捷指令

### 服务端信息 | Server

windows server

### 移动端信息 | Smartphone

ios18

**Comment by Jeric-X** [comment]
显然，这是iOS的问题





------------------ 原始邮件 ------------------
发件人: 解忧杂货店 ***@***.***&gt;
发送时间: 2024年9月27日 09:54
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] ios快捷指令 自动同步命令运行过程中运行其他快捷指令会中断 (Issue #133)





 
错误描述 | Describe the bug
 
ios快捷指令 自动同步命令运行过程中运行其他快捷指令会导致自动同步中断，好像只能同时运行一个快捷指令
 
复现步骤 | Steps to Reproduce
 
自动同步命令运行过程中运行其他快捷指令
 
截图 | Screenshots
 
No response
 
服务端信息 | Server
 
windows server
 
桌面端信息 | Desktop
 
No response
 
移动端信息 | Smartphone
 
ios18
 
其他附加信息 | Additional context
 
No response
