### ISSUE TITLE
粘贴时无法复制文件名字

### ISSUE THREAD

**Issue by lzy755277** [Jeric-X/SyncClipboard#137]
### 错误描述 | Describe the bug

我在windows上拷贝了一份word文档，在ios及ipad上的“文件”中粘贴显示为Office Open XML字处理文稿，希望能够修复一下使文档名字出现

### 复现步骤 | Steps to Reproduce

在描述中有

### 服务端信息 | Server

坚果云

### 桌面端信息 | Desktop

Windows 10 22H2 Synclipboard Version:2.8.6

### 移动端信息 | Smartphone

IOS 18.1beta4 IpadOS 18.1beta4

**Comment by Jeric-X** [comment]
改不了，ios的快捷指不支持设置名字
