### ISSUE TITLE
坚果云服务器貌似有点bug，求如何解决

### ISSUE THREAD

**Issue by lzy755277** [Jeric-X/SyncClipboard#138]
### 错误描述 | Describe the bug

我使用了一会同步功能后，坚果云服务器显示报错。所有设备都连不上。我配置的是3秒轮询一次。
![Uploading 屏幕截图 2024-10-16 202339.png…]()

### 复现步骤 | Steps to Reproduce

在描述中

### 服务端信息 | Server

坚果云

**Comment by lzy755277** [comment]
![屏幕截图 2024-10-16 202339](https://github.com/user-attachments/assets/f7c6e08b-40f2-4351-a358-639341ffe35e)

**Comment by Jeric-X** [comment]
坚果云不再适合作为自动同步的服务器了
