### ISSUE TITLE
Nas上通过 docker 部署，手机端使用 ipv6 访问，会报错误。

### ISSUE THREAD

**Issue by zhiquan304** [Jeric-X/SyncClipboard#145]
### 错误描述 | Describe the bug

安卓使用 HTTP快捷方式运行。报如下错误：
执行失败： unexpected end of stream on http://Na域名:5033/...
\n not found: limit=0 content=…

### 复现步骤 | Steps to Reproduce

正常设置即可

### 服务端信息 | Server

服务端不知道如何看报错，请在readme中指出

### 移动端信息 | Smartphone

OPPO ACE3

### 其他附加信息 | Additional context

排查了一天，发现需要在Nas 的Docker 中 appsettings.json 加上这么一串配置：

"""bash
    "HttpIPv6": {
      "Url": "http://[::]:5033"
    }
"""

**Comment by Jeric-X** [comment]
确实该加ipv6的。你试一下只把原来的0.0.0.0改成*可以绑定ipv6吗，可以的话能直接提个PR就更好了





------------------ 原始邮件 ------------------
发件人: ZhiQuan304 ***@***.***&gt;
发送时间: 2024年11月10日 19:06
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] Nas上通过 docker 部署，手机端使用 ipv6 访问，会报错误。 (Issue #145)





 
错误描述 | Describe the bug
 
安卓使用 HTTP快捷方式运行。报如下错误：
 执行失败： unexpected end of stream on http://Na域名:5033/...
 \n not found: limit=0 content=…
 
复现步骤 | Steps to Reproduce
 
正常设置即可
 
截图 | Screenshots
 
No response
 
服务端信息 | Server
 
服务端不知道如何看报错，请在readme中指出
 
桌面端信息 | Desktop
 
No response
 
移动端信息 | Smartphone
 
OPPO ACE3
 
其他附加信息 | Additional context
 
排查了一天，发现需要在Nas 的Docker 中 appsetting.json 加上这么一串配置：
 
"""bash
 "HttpIPv6": {
 "Url": "http://[::]:5033"
 }
 """
