### ISSUE TITLE
视网络情况自动切换本地服务端和 WebDAV

### ISSUE THREAD

**Issue by RarityBrown** [Jeric-X/SyncClipboard#147]
### 描述你想添加的功能 | Describe the feature you'd like

需求背景：

对于禁止内网通信的网络环境，希望优先走 WebDAV 以保证同步；
对于允许内网通信的网络环境，希望优先走内网以提高安全性和节约 WebDAV 流量。

大致有两种思路，作者认为哪种更合理/便于实现：

1. 匹配 WiFi 的 SSID，用户手动维护两列表：走内网的 SSID 列表、走 WebDAV 的 SSID 列表。其他 SSID 默认服从全局设置。
2. 优先尝试内网，超时后尝试 WebDAV
    1. 对于有另一些需求的用户，可以实现类似的优先尝试 WebDAV，超时后尝试内网？
    2. 还有用户可能需要同时执行两种同步方式以保证同步成功率？

### 描述你正在使用的替代方案 | Describe alternatives you are using

在不同的网络环境中手动切换

**Comment by Jeric-X** [comment]
不会增加这个功能，建议从自定义路由表/DNS/代理服务器等角度实现不同网络环境中的服务器切换

**Comment by RarityBrown** [comment]
“自定义路由表/DNS/代理服务器等角度实现不同网络环境中的服务器”切换感觉只能针对 `SyncClipboard.Server` 的“独立服务器”和“客户端内置本地服务器”间切换的情况？issue 提到的同步方案选择 WebDAV 服务器还是 `SyncClipboard.Server` 间的切换似乎目前只能还是依赖于客户端？

不考虑在软件内部增加自动化切换功能的话，是否方便为桌面客户端提供一个 CLI 接口，方便本地使用 sh, bat, py 等脚本自动化切换

**Comment by Jeric-X** [comment]
cli接口可能之后会加吧，暂时可以使用一个workaround，准备好两个配置文件，然后用脚本kill掉进程→替换配置文件→启动软件
