### ISSUE TITLE
重新连接网络之后自动重试功能

### ISSUE THREAD

**Issue by goow-auk** [Jeric-X/SyncClipboard#155]
### 描述你想添加的功能 | Describe the feature you'd like

目前客户端可以设置重试次数和超时时间，但在合盖一段时间后，例如几个小时之后，只能手动重新开启剪切板同步功能。
应该可以通过修改超时时间和重试次数来解决，但是想请问能否考虑添加重新连接网络之后自动重新尝试的功能？

**Comment by Jeric-X** [comment]
按一下ctrl + c应该就能触发重连了。
断网重连我有考虑加上的，但是好像无法解决你的问题。笔记本合盖断线通常不是网络问题，是windows的问题，锁屏状态下多次访问剪贴板会被windows阻止，如果仍然坚持访问剪贴板会有概率导致此次运行永久无法访问剪贴板，重试次数本质上是为了这个加的

**Comment by goow-auk** [comment]
> 按一下ctrl + c应该就能触发重连了。 断网重连我有考虑加上的，但是好像无法解决你的问题。笔记本合盖断线通常不是网络问题，是windows的问题，锁屏状态下多次访问剪贴板会被windows阻止，如果仍然坚持访问剪贴板会有概率导致此次运行永久无法访问剪贴板，重试次数本质上是为了这个加的

了解了🫡，感谢回复
