### ISSUE TITLE
请问安卓端接收到图片和文件应该如何保存

### ISSUE THREAD

**Issue by a1751504** [Jeric-X/SyncClipboard#16]
安卓端没有保存按钮，是否可以考虑想个办法保存下来
![Screenshot_2023-10-03-08-44-25-056_ch.rmy.android.http_shortcuts.jpg](https://github.com/Jeric-X/SyncClipboard/assets/31113826/8e93b738-7fa2-4c62-b251-2e5fb4ca9f9f)

**Comment by Jeric-X** [comment]
很奇怪啊，我的设备上右上角是有保存分享按钮的，可能是HTTP Request Shortcuts的适配问题
![Screenshot_2023-10-03-14-30-53-675_ch rmy android http_shortcuts](https://github.com/Jeric-X/SyncClipboard/assets/10058586/7d9252a1-0864-44ff-b5ed-d7a1b7e8c409)
绕过这个展示页面的方法
1. 分别点击这两个项目进行修改，下面的流程做两次

![Screenshot_2023-10-03-14-36-16-758_ch rmy android http_shortcuts](https://github.com/Jeric-X/SyncClipboard/assets/10058586/21c87c54-8387-475e-bd2b-83b1a55d3e40) 

2. 
<img width="600" alt="Screenshot_2023-10-03-14-36-45-070_ch rmy android http_shortcuts" src="https://github.com/Jeric-X/SyncClipboard/assets/10058586/c01c17a4-c40e-47cc-a9c5-0c7080036ddb"> 

3. 把框里的内容改成0 

<img width="600" alt="Screenshot_2023-10-03-14-37-06-177_ch rmy android http_shortcuts" src="https://github.com/Jeric-X/SyncClipboard/assets/10058586/c2b50e73-94d3-4a69-baf0-7feeda376e96"> 
 
这样每次下载文件就都会跳转到浏览器下载了
  
  
`使用浏览器下载` → `基本设置`里可以选择用哪个浏览器，我给默认成chrome了，不知道没装的话会怎样，可以手动修改一下，后续我会修改一下同步到github

**Comment by Jeric-X** [comment]
我再看看吧，有点麻烦
安卓上如果有比较好的自动化工具请推荐给我，至少能发送http请求，能直接运行代码最好

**Comment by a1751504** [comment]
还真没有啥更好的选择了，哈哈，有空折腾的话修修吧，没空就先鸽了，指不定哪天就看到啥解决方案了

**Comment by Jeric-X** [comment]
加一个妥协的方法，打开浏览器时同时会复制下载地址，自动下载失败的话手动粘贴到地址栏可能可以下载，这很不自动化
更新一下安卓端的脚本https://github.com/Jeric-X/SyncClipboard/blob/master/script/shortcuts.zip

不过也有可能失败，我的nextcloud有点低，而且还是直接局域网访问(也是没法直接下载，但是直接503没有任何信息)。看你的报错可能是触发了Nextcloud的跨站保护机制，在涉及内网穿透/反代的场景可能也有坑

**Comment by Jeric-X** [comment]
破案了，我更新了一下HTTP Request Shortcuts右上角的按钮也没了，得想办法降级一下

**Comment by a1751504** [comment]
可以了！谢谢谢谢

**Comment by Hwegcghewyg** [comment]
纯小白表示看不懂，连到底怎么弄都看不懂

**Comment by Jeric-X** [comment]
@Hwegcghewyg 这个问题应该已经解决了，上面对话里的操作完全忽略就好。你可以根据首页的readme一步一步操作，如果哪里有问题/不会操作可以简单描述一下（和这个issue不相关的话最好新开一个issue），说实话我也不知道怎么写教程，所以还需要你提一下具体哪不懂/卡在哪里了，这样我也可以逐渐完善首页readme

**Comment by Hwegcghewyg** [comment]
JericX ***@***.***> 于 2023年10月19日周四 00:46写道：
