### ISSUE TITLE
内置服务器上传下载服务报错

### ISSUE THREAD

**Issue by Zhou-b** [Jeric-X/SyncClipboard#25]
![Snipaste_2023-12-28_17-23-50](https://github.com/Jeric-X/SyncClipboard/assets/70552661/75741542-7f06-4946-b643-d494d55e3f68)

**Comment by Jeric-X** [comment]
尝试修复了，从这个地址下载看看有没有解决吧 https://github.com/Jeric-X/SyncClipboard/actions/runs/7347791494  
如果还有问题的话，麻烦把配置界面的截图或者配置文件发一下
