### ISSUE TITLE
内置服务器用户名密码设置出错

### ISSUE THREAD

**Issue by Atlantis-Gura** [Jeric-X/SyncClipboard#26]
环境：Windows 11 23H2 正式版

问题描述：如下图，将客户端内置服务器用户名设置为 user，密码为 password。

![image](https://github.com/Jeric-X/SyncClipboard/assets/97673767/b33b128e-2cd3-4089-8dbb-57186f263865)

配置完成后，再打开内置服务器设置，用户名会变为之前所设置的密码，如下图。此问题并不影响软件的正常工作。

![image](https://github.com/Jeric-X/SyncClipboard/assets/97673767/d5ce331d-66ac-409b-87b7-cd9e11c2d961)

此外，还有一个小问题，任务管理器显示 Win 客户端在后台时会一直有一个 0.1MB/s 的磁盘用量，请问这个能否继续优化？

![image](https://github.com/Jeric-X/SyncClipboard/assets/97673767/112a259c-1e77-4488-9c4f-8f008c54883e)

p.s. 软件做的很棒，加油！独立服务器如果能部署到docker就更方便啦

**Comment by Jeric-X** [comment]
感谢反馈，深夜看到这个问题要被自己笑死，常年默认用户名密码难怪发现不了

磁盘io问题：服务器会把客户端剪切板存到文件里，客户端查询的时候服务器就会有一个读取磁盘的操作，每次读取也就几byte，0.1MB/s看起来是windows最小单位，如果优化的话可以把信息存到内存里，可能以后会优化。开混合模式应该也不会有磁盘占用

Docker镜像考虑过或者说一直想做，但是目前一窍不通，只能说遥遥无期

**Comment by Atlantis-Gura** [comment]
谢谢回复，开启混合模式之后确实不再有磁盘占用。

我又仔细看了一遍readme里写的可以通过Webdav服务器实现多设备之间的同步，那感觉也没太大必要专门再做独立服务器的镜像了。当然如果以后有需要我也很乐意帮忙。
