### ISSUE TITLE
[功能请求/建议] 独立服务端的容器化

### ISSUE THREAD

**Issue by Atlantis-Gura** [Jeric-X/SyncClipboard#27]
https://hub.docker.com/r/gurashark/syncclipboard-server

这是我昨晚拿 Releases 里的服务端文件打包的镜像，我自己测试了基础功能应该没问题，有兴趣可以在 Docker 环境测试下，docker cli 命令如下：
```
docker run -d \
  --name=syncclipboard-server \
  -p 5033:5033 \
  --restart unless-stopped \
  gurashark/syncclipboard-server:latest
```
如果可能的话，作者也可以在项目文件夹下创建 Dockerfile（可以使用 ASP.NET SDK 镜像作为编译镜像并以 ASP.NET Core runtime 作为基础镜像），一步实现独立服务端的源码编译+容器化，更方便一些。

**Comment by Jeric-X** [comment]
感谢你的测试，我已经开始着手搞了

**Comment by Jeric-X** [comment]
@Atlantis-Gura 
我可以获得你在Docker Hub仓库里readme的markdown源码吗，感觉你写的已经很好了，我如果原封不动再照着写一遍就有一种抄袭的感觉。
你可以在结尾处加上readme written by，或者提PR合并到这个仓库的`docker`分支下的`src/SyncClipboard.Server/README_DOCKER.md`文件
