### ISSUE TITLE
mac客户端剪贴板上的图片变成了lib中的缓存文件路径，无法正常粘贴图片

### ISSUE THREAD

**Issue by fankwong** [Jeric-X/SyncClipboard#31]
mac客户端剪贴板上的图片变成了lib中的缓存文件路径或者文件，无法正常粘贴截图/图片
![图片](https://github.com/Jeric-X/SyncClipboard/assets/6179270/389df769-f2a2-459e-9498-b2c2f36462bf)

**Comment by Jeric-X** [comment]
确认是问题了，微信中无法粘贴图片

**Comment by Jeric-X** [comment]
https://github.com/Jeric-X/SyncClipboard.Desktop/releases/tag/v0.4.2

**Comment by fankwong** [comment]
新版本问题修复，目前使用良好，十分感谢🙏
