### ISSUE TITLE
macOS arm 版安装提示安装包已损坏

### ISSUE THREAD

**Issue by slarkcoder** [Jeric-X/SyncClipboard#32]
Mac 为 M1 版的 Macmini，系统为 14.2.1，安装包测试的 0.4.2，arm 版提示安装包损坏，x86 测试正常

**Comment by Jeric-X** [comment]
可以试试以前的版本有没有问题吗，我手里没有M1 mac，如果以前的没问题可能只是这次build有问题，重新build一下就好，如果一直有问题，我好像也没什么能做的了，得再想办法

**Comment by Jeric-X** [comment]
https://github.com/Jeric-X/SyncClipboard/actions/runs/7410349138

**Comment by Jeric-X** [comment]
参考了一些搜索结果，macOS可能会主动阻止运行未签名的软件，如果下面的方法你没有使用过也可以尝试一下
https://github.com/lyswhut/lx-music-desktop/issues/530
https://www.scwcd.cn/archives/34.html

**Comment by slarkcoder** [comment]
> https://github.com/Jeric-X/SyncClipboard/actions/runs/7410349138 这是最新主线的build，可以试试这个

测试了主线，以及 0.4.0，0.4.1 版本的 macOS arm 版， arm 版都打不开，x86 的都没问题。macOS 已经允许安装任何来源的软件，根据提示，应该不是 macOS 阻止运行未签名的软件。

<img width="260" alt="Snipaste_2024-01-07_16-29-54" src="https://github.com/Jeric-X/SyncClipboard/assets/8657857/9f1c1523-3bc8-4b74-9604-4cf32f33d1ed">

**Comment by slarkcoder** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/530

试了这个，可以解决！感谢大佬！

**Comment by dangehub** [comment]
我也遇见这个问题了，贴一下具体解决办法：终端输入`sudo xattr -rd com.apple.quarantine /Applications/SyncClipboard.app`

**Comment by jianqiao0313** [comment]
> sudo xattr -rd com.apple.quarantine /Applications/SyncClipboard.app

好使，感谢大佬
