### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by 328902301** [Jeric-X/SyncClipboard#33]
你好，开发者！

  能否测试一下ios端快捷指令的坚果云同步服务，坚果云同步出现问题，Nextcloud官方和自建的都正常。

  在1月19号的时候使用快捷指令同步到坚果云是可以的，但是第二天就开始无法同步数据，Windows端的同步正常运行。一开始怀疑是账号被限制的问题，重新注册了新号还是相同的问题。

  使用ios后台的抓包，可以看到上传了与剪切板文件相同大小的数据包，数据上传到了坚果云服务器，但是在坚果云内无法查看到，同时坚果云同步到ios端也不行。
![Clipboard 22 Jan 2024 at 09 26](https://github.com/Jeric-X/SyncClipboard/assets/117328786/02cbc7ff-2373-4b92-a2da-f985424fcd76)

  另外有可能的话，可以测试一下日本InfiniCLOUD网盘，赠送的网盘空间比较大，传输速度也比Nextcloud快一些，作为剪切板同步是个不错选择，就是有些兼容问题。ios上传服务正常，下载服务正常。Windows下载服务正常，上传服务有401错误。
![3vgnbkky rea](https://github.com/Jeric-X/SyncClipboard/assets/117328786/f039735b-96a6-47c1-a81e-ff1efa8bf0c6)

**Comment by Jeric-X** [comment]
坚果云我这边测试还是正常的，可以说一下错误细节吗。手动触发快捷指令的上传或下载，失败时应该会有某种形式的错误信息提示

**Comment by 328902301** [comment]
不好意思，发现可以了，原来是捷径多了6个actions的原因。
因为测试了几个网盘是否可用，几家网盘捷径配置来回复制，就比原版多了6个actions，导致无法上传。
③号是作者捷径修改的；①号是来回复制做好的坚果云配置，无法同步；②号是③号复制修好后的配置，可以正常运行；
刚好给大家提供一个错误案例😓
![1111](https://github.com/Jeric-X/SyncClipboard/assets/117328786/024b2f7f-c920-4e82-8336-928b0d625da0)

**Comment by 328902301** [comment]
经过作者提示正常运行，又测试了一下，终于发现问题所在。

ios端填写的路径有问题，坚果云同步的路径是https://dav.jianguoyun.com/dav/自定义文件夹/

这个路径在电脑端是没有问题的，但是在ios捷径中，需要把最后/去掉，不然无法同步https://dav.jianguoyun.com/dav/自定义文件夹，这个也算是几个网盘里唯一有这样问题的，算是给大家一个错误提示吧！

**Comment by Jeric-X** [comment]
原来如此，之后我会更新快捷指令自动去掉最后的斜线或者在readme里写明要填入不带斜线的url
InfiniCLOUD测试过了，适配的话需要更改代码，还需要一段时间

**Comment by 328902301** [comment]
好的，谢谢！

**Comment by Jeric-X** [comment]
https://github.com/Jeric-X/SyncClipboard/releases/tag/v2.6.1
新版本支持InfiniCLOUD了

**Comment by 328902301** [comment]
尊敬的GitHub开发者，

我怀着无比的感激之情，写下这封信来表达我对您无私奉献的感谢。您的不懈努力与持续更新，使得我们能够享受到优秀的软件产品。您的热情投入与对技术的热爱，成就了我们使用的每一款软件。在您的努力下，软件不断完善，功能更加强大，用户体验也愈发优秀。

您的贡献不仅仅是代码的提交，更是对开源精神的践行与传承。您的无私奉献，推动了整个开源社区的发展，为我们提供了学习的机会和分享的平台。在这个充满创新与挑战的世界里，您的存在是如此珍贵与重要。

感谢您为开源社区所做的一切努力，感谢您为我们带来的优秀软件。在未来的日子里，我期待着与您共同见证技术的进步，共同成长。再次感谢您的辛勤付出！

以上由ChatGPT帮本人代写。

开个小玩笑，经过一周多的折腾，本人主要使用场景是 Windows 端和 iOS 端的同步，现在主要是通过家庭自建服务器进行同步，基本可以做到无缝同步。测试的服务器有 Nextcloud 的 The Good Cloud （2GB）和 Tab.Digital （8GB），坚果云，InfiniCLOUD，以及云服务自建的 Nextcloud 和家庭自建的 SyncClipboard 。

建议轻度使用的话坚果云就可以了，速度快，不过就是流量太少了，只适合轻度文字同步。重度使用用户建议自建服务器和 InfiniCLOUD ，自建服务器没什么可说的，速度快，没有审核。InfiniCLOUD 是日本网盘，速度也非常可以，非常推荐不想折腾的用户，赠送的空间也比较大。Nextcloud 的服务器比较远，延迟会高一些，但也足够使用了。

**Comment by 328902301** [comment]
另外提一个功能上的小建议：是否可以增加对文件格式类型的判断，比如png、rar、zip、dmg 等等，电脑端平时使用的时候，总是会复制各种各样的文件类型，这时候总是会同步到服务端。能否在同步前先进行判断，允许的文件类型再同步服务端。

**Comment by Jeric-X** [comment]
很好的建议，记在小本上了

**Comment by lyscop** [comment]
![](https://i.vgy.me/dkYUpZ.png)

![](https://i.vgy.me/xSETxW.png)

问下这样设置是对的嘛

**Comment by Jeric-X** [comment]
@lyscop
SyncClipboard.Server和WebDAV服务器是二选一的关系，不用这样操作
如果使用InfiniCLOUD，你需要按照教程开启Apps Connection (https://infini-cloud.net/en/support_account_login-settings_apps.html)  
  
开启之后这三行就是地址的前缀、用户名、密码。你需要在根目录创建一个文件夹`SyncClipboard`，要设置的地址是`https://.../dav/SyncClipboard`
![ygz5lxdr 1bb](https://github.com/Jeric-X/SyncClipboard/assets/10058586/1d940cf3-09b9-4423-bdc3-5105855c3f01)
