### ISSUE TITLE
Windows端可以添加快捷键开启关闭剪切板同步，图片同步嘛

### ISSUE THREAD

**Issue by lyscop** [Jeric-X/SyncClipboard#34]
想能快捷键代替邮件通知栏图标点击勾选，图标显示不同颜色状态

另外，ios快捷指令有办法在桌面或者通知栏，小组件快捷开启关闭嘛

**Comment by Jeric-X** [comment]
快捷键可以开发
ios快捷指令不就是这样使用的吗？没懂

**Comment by lyscop** [comment]
> 快捷键可以开发 ios快捷指令不就是这样使用的吗？没懂

有个快捷指令的问题，用的自动的，添加快捷图标到桌面上了，点击一下运行，没办法关闭，到快捷指令APP里面也没办法关闭，有没有办法点桌面上的开启，再点下关闭运行同步指令

**Comment by Jeric-X** [comment]
桌面图标这个没法解决，想关闭的话只能在多任务界面退出快捷指令APP的后台(如果之前没打开过快捷指令APP，新打开再退出后台就行)
放一个快捷指令的桌面小组件的话用起来就比较正常了，就是占地方大了点
