### ISSUE TITLE
MacOS客户端不支持跳过证书校验

### ISSUE THREAD

**Issue by feranwq** [Jeric-X/SyncClipboard#37]
自建 Server 没有域名,希望可以支持 insecure 选项

**Comment by Jeric-X** [comment]
新版本增加了相关选项
![hnbueol1 o1u](https://github.com/Jeric-X/SyncClipboard/assets/10058586/5b570276-72dc-4c34-97b7-9fdc70130dce)

**Comment by feranwq** [comment]
已验证好使, 祝新年好🎆
