### ISSUE TITLE
设置了webdev，传照片有点慢，换成本机服务器的时候一定要勾选内置服务器嘛

### ISSUE THREAD

**Issue by lyscop** [Jeric-X/SyncClipboard#38]
使用webdev取消勾选内置服务器，取消勾选本机服务器，能正常同步
使用192.168.0.101:5033，除了勾选本机服务器，还要勾选内置服务器才能正常同步呀

使用webdev服务器，同时勾选了内置服务器传照片也快了，那就是不管使用本机还是webdev都勾选着内置服务器嘛

![0w5lqc0t 1qa](https://github.com/Jeric-X/SyncClipboard/assets/63564691/3c017a8f-1d4e-48b5-8611-46613630aa4e)

**Comment by lyscop** [comment]
![uvhbe4je 3l2](https://github.com/Jeric-X/SyncClipboard/assets/63564691/be7c7a68-ff02-4d5e-bf63-55b843adb558)

**Comment by Jeric-X** [comment]
两种思路：
#### 1、使用webdav（teracloud.jp或者坚果云之类的网盘）
- 关闭`内置服务器`
- 关闭`使用本机服务器`
- 填写网盘地址、用户名、密码
#### 2、使用内置服务器
- 开启`内置服务器`（这个选项的意思是在自己的电脑上开启一个专用的网盘当服务器）
- 开启`使用本机服务器`（这个选项的意思是直接用`内置服务器`，地址用户名密码就不用你自己写了，当然你也可以不开，手动填192.168.0.101:5033，效果是一样的。开启这个选项后，地址、用户名、密码这些以前填过信息会以淡灰色显示，不生效，并且无法修改）

**Comment by lyscop** [comment]
明白了，切换的时候要勾选内置和本机，不如就保持勾选内置

**Comment by Jeric-X** [comment]
正常来说，开不开内置服务器没有影响，我觉得是巧合，日本服务器可能不是很稳吧
