### ISSUE TITLE
同步照片命名能到秒嘛，使用本地服务器拷贝图片到电脑，同一分钟内拷贝2张图片名字为分钟会覆盖

### ISSUE THREAD

**Issue by lyscop** [Jeric-X/SyncClipboard#39]

**Comment by Jeric-X** [comment]
说详细一点，从什么设备拷贝，粘贴到什么设备，两端都有这么多选择（ios/android/linux/mac/windows），甚至每个移动端的方案也可能不止一个
大概分析一下，我没有用时间命名图片的操作，大概是移动端分享系统的自动命名，如果是这样的话无法解决。粘贴端遇到同名文件粘贴时应该会提醒重命名吧

**Comment by lyscop** [comment]
从ios，复制相册的照片后，使用手动同步的快捷指令上传照片，Windows自动下载

命名为 Clipboard 2024年2月18日 23.17

![3ba45sga ovw](https://github.com/Jeric-X/SyncClipboard/assets/63564691/328b5917-ff95-46ba-92ec-cd0a33c480fc)

**Comment by Jeric-X** [comment]
其实你可以直接分享，直接分享的话IOS不会改名，如下图，这里没有就在下面，可以置顶到这
![nfhraw2e 2fk](https://github.com/Jeric-X/SyncClipboard/assets/10058586/ef4557de-665e-4e9e-8e79-b2b2a91cacfc)

**Comment by lyscop** [comment]
感谢，好方便
