### ISSUE TITLE
Android 修改配置文件的时候最好建议在文档中提示一下去掉 url 后的斜杠

### ISSUE THREAD

**Issue by huaxianyan** [Jeric-X/SyncClipboard#40]
我一开始使用的是方案 2 配合模块，但是后来发现在 Android 14 上模块并不能很好的工作，这样一来就不如方案 1 了

但是方案 1 修改完变量后一开始看到请求都是 404，抓包看了看发现请求地址里有双斜杠

这时候才看到方案 2 的导入文件注释里有这么一句

希望作者还是能够在文档中着重提示一下这句，避免后来的用户再走弯路

**Comment by Jeric-X** [comment]
你说得对，写那个注释的时候就应该排查所有地方，是我疏忽了
