### ISSUE TITLE
一个小bug：icon Bug 

### ISSUE THREAD

**Issue by robin758** [Jeric-X/SyncClipboard#41]
# 配置

- windows 10 home
- clipboard ui版
- 配置成功可以转发剪切板

# Icon Bug

- 所有的 icon 都无法显示
![image](https://github.com/Jeric-X/SyncClipboard/assets/83524955/6bb6e770-f40b-4951-a496-7a97c248f032)

**Comment by Jeric-X** [comment]
看readme里的依赖，安装一下图标字体

**Comment by robin758** [comment]
> 看readme里的依赖，安装一下图标字体

我的我的，感谢❤

**Comment by robin758** [comment]
> 看readme里的依赖，安装一下图标字体

我的我的，感谢❤
