### ISSUE TITLE
win10 剪切板BUG

### ISSUE THREAD

**Issue by 328902301** [Jeric-X/SyncClipboard#42]
Win10在最新的v2.7.1版本中，拷贝和剪切文件夹时会没反应，操作指令会被覆盖无效，快捷键操作和右键选择都是如此，不过拷贝和剪切文件以及文字都正常。

**Comment by Jeric-X** [comment]
发布v2.7.2了

**Comment by 328902301** [comment]
感谢，测试都正常了
