### ISSUE TITLE
复制excel表格数据被识别成图片

### ISSUE THREAD

**Issue by hzy11fk** [Jeric-X/SyncClipboard#43]
复制excel单元格数据的时候，被识别成图片上传，另外ios设备里复制备忘录里的内容也同样被识别成图片

**Comment by Jeric-X** [comment]
https://www.icloud.com/shortcuts/542ad23b33314b36807c05a5d8aa5c22

**Comment by hzy11fk** [comment]
> 尝试下这个快捷指令 https://www.icloud.com/shortcuts/542ad23b33314b36807c05a5d8aa5c22

谢谢您，ios备忘录复制被识别成图片的问题解决了，就是excel单元格复制成图片的问题还是需要您再看一看，我使用的版本是2.7.2

**Comment by hzy11fk** [comment]
> > 尝试下这个快捷指令 https://www.icloud.com/shortcuts/542ad23b33314b36807c05a5d8aa5c22
> 
> 谢谢您，ios备忘录复制被识别成图片的问题解决了，就是excel单元格复制成图片的问题还是需要您再看一看，我使用的版本是2.7.2

又尝试了一下，关掉图片轻松拷贝以后，excel单元格数据可以粘贴到其他地方了，就是依然是以图片形式上传

**Comment by Jeric-X** [comment]
感谢测试，Windows最新版应该修复了

**Comment by hzy11fk** [comment]
> 感谢测试，Windows最新版本应该修复了 https://github.com/Jeric-X/SyncClipboard/releases/tag/v2.7.3

感谢您的更新
