### ISSUE TITLE
苹果手机快捷指令放在后台自动关闭后，手机无法自动同步windows的剪贴板

### ISSUE THREAD

**Issue by CyberIKUN** [Jeric-X/SyncClipboard#44]
使用快捷指令的方式，苹果手机若不在快捷指令的界面，而是放到后台，会自动关闭，导致要不断地打开手机的快捷指令。

**Comment by CyberIKUN** [comment]
是否可以考虑通过蓝牙的模式传送剪贴板的内容，因为在有些情况下，比如连了公司的网络，但是手机不想连公司的网络，因为公司的网络会进行监控，这样手机和电脑不在一个局域网就不能互传了。若是通过三方服务器或者其他的方式的话就比较鸡肋且没必要，因为就只是设备内容互传，并不需要那么麻烦去配置一个三方服务器。

**Comment by Jeric-X** [comment]
> 使用快捷指令的方式，苹果手机若不在快捷指令的界面，而是放到后台，会自动关闭，导致要不断地打开手机的快捷指令。

快捷指令的后台也不是那么容易被杀掉吧，我使用的iPhone XS已经是很老的机器了，我自己测试可以稳定后台运行。要是网络出现波动倒是有会直接退出，这点没办法，快捷指令不提供类似try catch的机制，错了就直接退出了。你说的自动关闭有什么特征吗，就悄无声息的没了？

> 是否可以考虑通过蓝牙的模式传送剪贴板的内容，因为在有些情况下，比如连了公司的网络，但是手机不想连公司的网络，因为公司的网络会进行监控，这样手机和电脑不在一个局域网就不能互传了。若是通过三方服务器或者其他的方式的话就比较鸡肋且没必要，因为就只是设备内容互传，并不需要那么麻烦去配置一个三方服务器。

不会考虑蓝牙，现在移动端还没有正经的独立客户端，有很多限制，就比如说快捷指令并没有蓝牙相关的接口。
iOS的客户端基本永远不会有开发计划，因为没有后台设置/读取剪切版的权限。

加一个蓝牙的网络层也不是那么简单？开发的性价比很难说，不过这也是后话了

手机不信任公司提供的CA应该也不会太暴露太多信息吧，当然相比于你主页写的工作这方面我可能不是很懂。能连外部第三方服务器就连外部服务器吧，顶多速度慢一点
