### ISSUE TITLE
macos 支持任务栏始终显示 inactive 风格图标

### ISSUE THREAD

**Issue by feranwq** [Jeric-X/SyncClipboard#48]

**Comment by Jeric-X** [comment]
你的意思是想要颜色一直显示灰色，不管开关状态？

**Comment by feranwq** [comment]
> 你的意思是想要颜色一直显示灰色，不管开关状态？

我看了下, 我的需求应该是显示纯黑色, 和其他应用风格一致, 可能需要单独加个风格设置?
<img width="617" alt="pp1sldqw wfz" src="https://github.com/Jeric-X/SyncClipboard/assets/24955278/e6194301-25d7-4f72-a21e-7b8feb4526f4">

**Comment by Jeric-X** [comment]
从这种统一程度来看，黑色大概率是mac上的设计规范了
我观察了一下，确实，别的APP会在浅色系统主题下显示黑色，深色下变成白色，应该用的是类似SVG的格式，由系统改变颜色
这个应该会改，但是这样无法区分开关状态了，不知道怎么搞

**Comment by feranwq** [comment]
> 从这种统一程度来看，黑色大概率是mac上的设计规范了 我观察了一下，确实，别的APP会在浅色系统主题下显示黑色，深色下变成白色，应该用的是类似SVG的格式，由系统改变颜色 这个应该会改，但是这样无法区分开关状态了，不知道怎么搞

我看了下, 有类似开关状态的orbstack和clash都是 黑色/灰色切换

**Comment by Jeric-X** [comment]
https://github.com/Jeric-X/SyncClipboard/actions/runs/8316814829
可以试一下这个版本，在macOS上更改了图标颜色

**Comment by feranwq** [comment]
试了下黑白任务栏都很完美,ღ( ´･ᴗ･` )比心
