### ISSUE TITLE
mac客户端问题

### ISSUE THREAD

**Issue by fankwong** [Jeric-X/SyncClipboard#49]
问题1:mac客户端无法关闭dock上的程序而后台继续驻留在状态栏托盘；
问题2:mac客户端任何窗口在最前的情况下，按comm+q快速关闭窗口都是优先触发关闭syncclipboard的dock任务（然后整个syncclipboard就会退出）

**Comment by Jeric-X** [comment]
1. 任何软件在dock图标上右键退出都是直接退出吧……？应该会有某种方法让后台任务和dock栏图标分离，但我觉得没必要
2. 在mac上Command + Q是退出软件(除`访达`外)，Command + W是关闭窗口，我还是特意做的command + w的适配  

你可以用微信迅雷之类的带后台任务的软件测试，SyncClipboard和他们应该是一样的

**Comment by feranwq** [comment]
mac 应用有个 agent 模式可以自动隐藏 Dock 图标, 修改 Info.plist 即可, 不过我本地修改没有效果,可能还有其他因素影响
```
    <key>LSUIElement</key>
    <true/>
```
参考 https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement

**Comment by Jeric-X** [comment]
新版本优化了一下dock栏的展示，可以尝试一下
@fankwong @feranwq
