### ISSUE TITLE
拷贝CAD里的内容到 另一个cad窗口dwg图纸，拷贝的内容变成图片格式

### ISSUE THREAD

**Issue by chrisdong** [Jeric-X/SyncClipboard#50]
我从事建筑设计，经常从一个cad图纸里拷贝图纸到另一个cad窗口里，但是 syncClipboard默认把拷贝的cad图纸内容变成图片了，能否修复一下这个bug，现在我暂时关掉图片的功能，但有时候真的 拷贝图片的时候，又得打开。

**Comment by Jeric-X** [comment]
可以装一下这个软件吗 https://freeclipboardviewer.com/
关闭SyncClipboard的情况下，在CAD里拷贝内容，点击界面上的保存，并把保存.cl7文件上传上来
![ebcwvhw0 ejp](https://github.com/Jeric-X/SyncClipboard/assets/10058586/924d41c3-c32c-4c08-9f66-750f0f7b8798)

另外用的是具体哪个CAD软件，如果安装简单的话我可以自己装一个

**Comment by chrisdong** [comment]
Auto CAD 2010 和 天正建筑

**Comment by chrisdong** [comment]
[111.zip](https://github.com/Jeric-X/SyncClipboard/files/14611701/111.zip)
我压缩了一下 .cl7文件

**Comment by Jeric-X** [comment]
看一看这个问题解决了没有，[SyncClipboard.WinUI3](https://github.com/Jeric-X/SyncClipboard/actions/runs/8294593073/artifacts/1329060782)
