### ISSUE TITLE
PC上使用客户端自带的服务器的话，安卓端的url应该写什么

### ISSUE THREAD

**Issue by hsuromky** [Jeric-X/SyncClipboard#53]
![image.png](https://s2.loli.net/2024/03/29/SMwAsL8qzjEr5FJ.png)
我开了本机服务器，然后说是可免配置直接连接，那我手机上的话应该怎么操作，如果用autox.js的话，const url = 这里应该填什么的

**Comment by Jeric-X** [comment]
`http://ip:端口号`，ip是你电脑在局域网中的ip，端口号看你的图是5033

**Comment by hsuromky** [comment]
![0a1f8d12f5a761aac52cd824aab493d.jpg](https://s2.loli.net/2024/03/29/Ehsca9w6UM7k1go.jpg) 这是我手机上设置的

这是我电脑的ipconfig
![image.png](https://s2.loli.net/2024/03/29/WSPh6iBlxmc7JyF.png)

还是不对

**Comment by Jeric-X** [comment]
找一些成熟的局域网工具看看是不是网络问题，比如[远程桌面](https://play.google.com/store/apps/details?id=com.microsoft.rdc.androidx&hl=en_US)，或者你喜欢的工具

**Comment by hsuromky** [comment]
![Screenshot_2024-03-29-17-40-53-089_com.github.android-edit.jpg](https://github.com/Jeric-X/SyncClipboard/assets/117238021/f659a355-736f-4591-82ef-6261005bfbeb)

这个路径在哪

**Comment by hsuromky** [comment]
> 直接在地址栏里粘贴

好的谢谢，还是不行🤣🤣🤣

**Comment by hsuromky** [comment]
> 找一些成熟的局域网工具看看是不是网络问题，比如[远程桌面](https://play.google.com/store/apps/details?id=com.microsoft.rdc.androidx&hl=en_US)，或者你喜欢的工具

感谢作者，你这句话提醒我了，我试了下KDE Connect，都在局域网下 就是无法发现对方，然后我试着关了防火墙就正常了 现在问题就是怎么同步图片，我在电脑上用微信截了一张图 怎么在手机上直接粘贴这张图，我把“图片轻松拷贝”和“图片兼容性优化”打开了![qgtyqcdh.fwg.png](https://s2.loli.net/2024/03/30/Jekoz4XpuscMqAQ.png)

**Comment by Jeric-X** [comment]
[Autox.js](https://github.com/kkevsekk1/AutoX)也没提供向剪贴板内存放图片的接口，所以[Autox.js](https://github.com/kkevsekk1/AutoX)无法同步图片
只能用[HTTP Request Shortcuts](https://play.google.com/store/apps/details?id=ch.rmy.android.http_shortcuts)手动触发，下载图片后有分享按钮

**Comment by hsuromky** [comment]
换http request shortcuts可以传图片了。http request shortcuts相比autox.js的话，下载剪贴板只能手动点开软件点击”下载剪贴板“吗  不像autox.js的话“在后台时可以自动下载远程剪贴板文字到本地”

**Comment by Jeric-X** [comment]
[HTTP Request Shortcuts](https://play.google.com/store/apps/details?id=ch.rmy.android.http_shortcuts)无法自动同步。可以把快捷方式放到桌面，在支持的系统上可以放到通知栏开关的位置
而且这两个软件都没有能力直接设置图片类型的剪贴板。更根本的是，安卓上缺少不同APP之间非文字类型剪贴板的交互规范，两个软件配合使用吧

**Comment by hsuromky** [comment]
谢谢开发者，很好用，差点就错过
