### ISSUE TITLE
刚需新功能：大佬能否支持 alt+c 才触发剪切到服务端，alt+v才能粘贴服务端最新内容。这样，可以有选择性的跨设备共享，又不响应现有的复制粘贴功能

### ISSUE THREAD

**Issue by laughingchs** [Jeric-X/SyncClipboard#55]
非常感谢大佬贡献新功能，很赞，谢谢了。

刚需新功能：
能否支持 alt+c 才触发剪切到服务端，alt+v才能粘贴服务端最新内容。

好处：
1. 这样，可以有选择性的跨设备共享，又不响应现有的复制粘贴功能
2. 降低对服务器的压力
3. 用户也不用担心有隐私泄露的风险

**Comment by Jeric-X** [comment]
![c3el5h0j km0](https://github.com/Jeric-X/SyncClipboard/assets/10058586/521d1b15-7204-4d14-af27-91608cdbd5ef)
这两个快捷键可以无视剪贴板同步开关状态手动触发上传下载，不过你要额外按`ctrl + c`，`ctrl + v`

**Comment by laughingchs** [comment]
> ![c3el5h0j km0](https://private-user-images.githubusercontent.com/10058586/318168230-521d1b15-7204-4d14-af27-91608cdbd5ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Nzk3NjEsIm5iZiI6MTcxMTc3OTQ2MSwicGF0aCI6Ii8xMDA1ODU4Ni8zMTgxNjgyMzAtNTIxZDFiMTUtNzIwNC00ZDE0LWFmMjctOTE2MDhjZGJkNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA2MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1OTk1MDUyY2NiYTA3NzVjYWJlMWNhMjNiODM5YzZjMGYyMGUzZmFkZWU4NTQ2YTUxYzFjY2M3OWJjMDk0NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TU-qAOC6P9pW-yBL7b-bJHvHVfYphuOHsFvsj4FMf_s) 这两个快捷键可以无视剪贴板同步开关状态手动触发上传下载，不过你要额外按`ctrl + c`，`ctrl + v`

了解，非常感谢。但这个要按2次快捷键操作，有没有考虑再提供一组快捷键，支持我说的场景哈（这种场景还是很符合用户需求的，有需要再同步，没需要就不触发同步）

**Comment by Jeric-X** [comment]
在计划中，未来可期

**Comment by Jeric-X** [comment]
尝试加了这个功能，帮我测试一下吧，windows端是[SyncClipboard.WinUI3](https://github.com/Jeric-X/SyncClipboard/actions/runs/8497635519/artifacts/1372577284)，其他端从这个页面里下载
https://github.com/Jeric-X/SyncClipboard/actions/runs/8497635519

**Comment by goomoon** [comment]
> 尝试加了这个功能，帮我测试一下吧，windows端是[SyncClipboard.WinUI3](https://github.com/Jeric-X/SyncClipboard/actions/runs/8497635519/artifacts/1372577284)，其他端从这个页面里下载 https://github.com/Jeric-X/SyncClipboard/actions/runs/8497635519

测试过了，可以的；非常完美，功能太赞了，非常非常感谢
