### ISSUE TITLE
mac os下，有时会失效：从诊断日志里面看，已经显示拷贝的内容了，但远程服务器上的数据还是旧的

### ISSUE THREAD

**Issue by laughingchs** [Jeric-X/SyncClipboard#56]
问题：
mac os下，有时会失效：从诊断日志里面看，已经显示拷贝的内容了，但远程服务器上的数据还是旧的，有时通过快捷键重新触发上传能正常，有时哪怕通过快捷键重新触发上传，服务器数据还是旧的，也没显示哪里报错了。

环境：
mac os 13.2.1 (22D68)

修复：
重新启动环境，再触发一般又能正常

**Comment by Jeric-X** [comment]
log能发一下吗

**Comment by goomoon** [comment]
可以暂时忽略该问题，因为之前是我这边做了组合快捷键，先触发系统复制，过100ms，再触发操作上传操作，有可能是这100ms 时间不够，导致没衔接上。
