### ISSUE TITLE
BasicAuthentication was not authenticated. Failure message: Invalid Authorization Header

### ISSUE THREAD

**Issue by forrestgao** [Jeric-X/SyncClipboard#58]
我在独立ubuntu服务器上部署，输入用户名密码后报错：BasicAuthentication was not authenticated. Failure message: Invalid Authorization Header。不知道是什么问题，密码肯定输对了，抓包Authorization 字段也是正确的base64编码……

**Comment by Jeric-X** [comment]
设置成最简单的账号密码如123之类的试一下

**Comment by forrestgao** [comment]
> 设置成最简单的账号密码如123之类的试一下 Message ID: ***@***.***&gt;

可能我描述的不够清晰，密码是输对了的，如果输错密码会重新弹出输密码窗口，但输对密码确认后显示的页面不正常：HTTP ERROR 405

**Comment by Jeric-X** [comment]
> 如果输错密码会重新弹出输密码窗口

可以详细描述下你的操作吗，客户端没有重新弹出密码窗口的功能，你使用了浏览器，还是某些API调试工具？具体请求的HTTP方法、url是什么？

另外server启动的命令行是什么，是和Readme中描述的一模一样吗

**Comment by forrestgao** [comment]
> > 如果输错密码会重新弹出输密码窗口
> 
> 可以详细描述下你的操作吗，客户端没有重新弹出密码窗口的功能，你使用了浏览器，还是某些API调试工具？具体请求的HTTP方法、url是什么？
> 
> 另外server启动的命令行是什么，是和Readme中描述的一模一样吗

我是客户端提示连接不上服务器后用浏览器访问那个链接的……今天试了下服务器上装docker，利用docker方式部署是可以成功连接的……也算是解决问题啦。浏览器输对密码后会提示405，但不影响客户端连接。

**Comment by Jeric-X** [comment]
这个网址就不是用来直接访问的，如果有连接问题请描述客户端提示的信息或问题现象

**Comment by Jeric-X** [comment]
问题关闭了，如果还有问题可以重新打开或新提issue
