### ISSUE TITLE
怎么更新软件

### ISSUE THREAD

**Issue by hsuromky** [Jeric-X/SyncClipboard#61]
我手动删除了上个版本的目录，之后重新打开最新版，exe无法启动了，说是让我安装.net desktop runtime，可是我之前就已经安装过了，而且就算我点了是也没有跳转
![image](https://github.com/Jeric-X/SyncClipboard/assets/117238021/0433c815-dab6-45c4-8461-7d6a53a0096a)
![image](https://github.com/Jeric-X/SyncClipboard/assets/117238021/87bad971-3fb6-4ca8-9d0c-8910af7d3072)

**Comment by hsuromky** [comment]
> 我手动删除了上个版本的目录，之后重新打开最新版，exe无法启动了，说是让我安装.net desktop runtime，可是我之前就已经安装过了，而且就算我点了是也没有跳转 ![image](https://private-user-images.githubusercontent.com/117238021/320680573-0433c815-dab6-45c4-8461-7d6a53a0096a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjE2NzksIm5iZiI6MTcxMjYyMTM3OSwicGF0aCI6Ii8xMTcyMzgwMjEvMzIwNjgwNTczLTA0MzNjODE1LWRhYjYtNDVjNC04NDYxLTdkNmE1M2EwMDk2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMDA5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWM3NmE1Mjg5NTIwOTljNDlkZjc4OGY1MDNjZDI1YTE2NzkxMTQ2Y2MyZTAyNDdiNzM1N2U1ZTRhY2NlOWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Dp111vylq7Ick4LCgIy9rZg2dBFU1VW0VleVS_UBwRE) ![image](https://private-user-images.githubusercontent.com/117238021/320680599-87bad971-3fb6-4ca8-9d0c-8910af7d3072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjE2NzksIm5iZiI6MTcxMjYyMTM3OSwicGF0aCI6Ii8xMTcyMzgwMjEvMzIwNjgwNTk5LTg3YmFkOTcxLTNmYjYtNGNhOC05ZDBjLTg5MTBhZjdkMzA3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMDA5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWIxY2ZkMjZmYzQ4YTQ2YWRlMmUzZDA0MTY5NDBmNTQzNjUyMWI4ZDkwMDk0MDYyMWNlYmYwY2Q4ZWRiNmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OFprwIfMOsZv8Gj7Qf2KRHq2bC9d5j4SzCh4eQ9eHqo)

肯定是我软件更新的方法不对，请教一下开发者

**Comment by Jeric-X** [comment]
正常来说就是直接解压覆盖就可以了，配置文件目录保留(%AppData%\SyncClipboard\)，不过删了也就是配置丢了。以前能运行新版本肯定也能运行，你有没有没做别的操作？

尝试以下动作
- 下载旧版看能否打开
- 在CMD里运行`dotnet --list-runtimes`看一下是否有`Microsoft.AspNetCore.App 6.0.28`和`Microsoft.WindowsDesktop.App 6.0.28`
- 在CMD里运行`echo $PATH`查看结果是否有`C:\Program Files\dotnet\`记录，并且位置在`C:\Program Files (x86)\dotnet\`前边

**Comment by hsuromky** [comment]
(%AppData%\SyncClipboard)我删除了这个目录就可以了

**Comment by hsuromky** [comment]
一开始覆盖安装的时候一直提示我复制不进去，一直让我重试 我也没截图

**Comment by Jeric-X** [comment]
> (%AppData%\SyncClipboard)我删除了这个目录就可以了

啊？为什么，删的东西还在回收站吗，在的话能给我传一份吗



> 一开始覆盖安装的时候一直提示我复制不进去，一直让我重试 我也没截图

这个应该是程序还没退出吧，或者是出bug右下角托盘不显示但是任务管理器里还能看见进程

**Comment by hsuromky** [comment]
https://wwp.lanzoum.com/iNZ5S1ufmbgb
正好还在回收站 

一直重试确实应该是进程没有彻底结束，我删除旧版整个目录的时候提示我删除不成功也印证了这点
程序完全退出的情况下，我要更新就直接覆盖就好了吧

**Comment by hsuromky** [comment]
[sync.zip](https://github.com/Jeric-X/SyncClipboard/files/14913858/sync.zip)
蓝奏的下载链接怎么没了 我重新上传一下

**Comment by Jeric-X** [comment]
一般直接覆盖就好了，可能是因为新旧文件混用导致的问题
建议你删除网盘的token重新创建一个，上面我没说清楚，配置文件里带有网盘的账号密码，你的回复我已经第一时间删了

**Comment by hsuromky** [comment]
> 一般直接覆盖就好了，可能是因为新旧文件混用导致的问题 建议你删除网盘的token重新创建一个，上面我没说清楚，配置文件里带有网盘的账号密码，你的回复我已经第一时间删了

我现在重新上传了一下  能看到了吗

**Comment by Jeric-X** [comment]
我已经下载到了，我的意思是配置文件里存着你的账号密码，我应该让你自己提前删掉的

**Comment by hsuromky** [comment]
嗯嗯  谢谢开发者提醒，坚果云已经撤销授权了，自己不是程序员不知道这些 😂 

说到webdav,说是可以用webdav作服务器也可以，但是我当时也是稀里糊涂的操作，就是没成功（估计也是防火墙的原因）

话说比起本地的windows内置服务器，用webdav的话有什么优势吗

**Comment by Jeric-X** [comment]
内置服务器只能局域网内使用。WebDav取决于提供商的服务范围，坚果云显然是个广域网服务器，任何地方都能访问到

**Comment by hsuromky** [comment]
谢谢
