### ISSUE TITLE
安卓上传电脑显示空白，但提示上传成功（以前好好的更新后不知道怎么了）

### ISSUE THREAD

**Issue by dongbao66** [Jeric-X/SyncClipboard#62]
![1](https://github.com/Jeric-X/SyncClipboard/assets/95880227/adadc02a-a8af-4703-a22a-30fa49032471)
![2](https://github.com/Jeric-X/SyncClipboard/assets/95880227/80ad5f85-b714-4708-a2d1-7823f57b2899)
![3](https://github.com/Jeric-X/SyncClipboard/assets/95880227/07aae527-6223-4b0b-9123-f5630d6c4507)

电脑复制后，手机使用 HTTP快捷方式 下载剪贴板能够成功获取文本，但是手机复制后执行HTTP的上传剪贴板操作后，电脑却不能获取文本，电脑的剪贴板有一个空白。

**Comment by Jeric-X** [comment]
1. log发一下收到空白消息的那个时间点的，最好能体现从非空白变成空白的过程
2. 从什么版本更新的，就是从上个版本更新的吗
3. 安卓系统有更新吗
4. 打开`HTTP快捷方式`主界面，在软件主界面内点上传能成功吗

**Comment by dongbao66** [comment]
1.
![1](https://github.com/Jeric-X/SyncClipboard/assets/95880227/7d247fec-79c7-4ce6-ae92-4ad56a019dd7)

2.  2.74升上来的，HTTP也更新到最新版了，所以不知道是那个软件升级导致的，升级导致仅仅是猜测的原因。
3. 安卓系统没更新
4. 可以显示上传成功

**Comment by dongbao66** [comment]
发现问题，是我在下拉控制中心点击磁贴导致的。
1.
![2](https://github.com/Jeric-X/SyncClipboard/assets/95880227/c1ecbb9b-e9f2-4f5b-8aee-d22f54f633e7)
2.
![3](https://github.com/Jeric-X/SyncClipboard/assets/95880227/dd830b59-72f9-4f0e-831b-acdd4ac9e627)

使用这种方式就会导致电脑，在上传后显示空白。
而再软件内点击上传到剪贴板，就会正常同步。
但是以前点击磁贴是会正常上传同步的，可能是更新到最新版HTTP软件导致的吧

**Comment by ningcol** [comment]
我的安卓上传也是，服务器上没有内容

**Comment by Jeric-X** [comment]
开启服务器，关闭桌面端的剪贴板同步。或者使用独立服务器，并退出所有桌面端
然后触发一次空白内容的上传，在服务器文件里查看SyncClipboard.json是什么内容
另外log再稍往前一点，可以多截一点

**Comment by dongbao66** [comment]
明天试试，我用的webdav同步，应该怎么搞

**Comment by Jeric-X** [comment]
就直接看文件夹下SyncClipboard.json里边是什么就好了

**Comment by Jeric-X** [comment]
如果没有其他桌面端运行的话(桌面端会自动删除不合法的SyncClipboard.json并创建一个Type为Text的空剪贴板)，就是安卓端APP没获取到剪贴板内容了(或者说获取到空字符串)，但是我自己一直没复现，不知道怎么回事

**Comment by dongbao66** [comment]
是安卓点击上传剪贴板，pc获取不到为空啊

**Comment by dongbao66** [comment]
1.是webdav长传显示空白时，网盘文件夹下SyncClipboard.json里边的内容
![1](https://github.com/Jeric-X/SyncClipboard/assets/95880227/069235a8-82ee-4d20-853f-7514354631b6)

2.是上传空白是，电脑的log日志
![2](https://github.com/Jeric-X/SyncClipboard/assets/95880227/b02f746a-577a-409c-b5ac-d46d9f3cfca6)

**Comment by dongbao66** [comment]
![4](https://github.com/Jeric-X/SyncClipboard/assets/95880227/4542a2b5-9496-4df9-b1c0-baaed7d63b7e)

**Comment by Jeric-X** [comment]
@dongbao66 
大概是手机端APP的问题。跟着我的视频创建一个快捷指令，在手机上随便复制点什么，分别在控制中心和软件内使用，看看能不能调用默认浏览器使用百度搜索正在复制的东西

https://github.com/Jeric-X/SyncClipboard/assets/10058586/d7d7cca5-35cb-49db-bdbc-714a3420728c

@ningcol 
如果app内也不成功，更多的想考虑是系统对app读取剪贴板有限制，是和lz一样以前有成功过吗？

**Comment by dongbao66** [comment]
@Jeric-X 
两个方式都可以调用默认浏览器，通过百度搜索正在复制的东西

**Comment by Jeric-X** [comment]
> 两个方式都可以调用默认浏览器，通过百度搜索正在复制的东西

好好好，这么玩是吧，现在我不会了

**Comment by dongbao66** [comment]
哈哈哈 bug那只能暂时搁置了

**Comment by Jeric-X** [comment]
再帮我试一下吧，看一下能否上传成功，以及提示什么，粘贴的代码以这里的为准

https://github.com/Jeric-X/SyncClipboard/assets/10058586/24ec120c-4aae-4380-a5ec-3d7a1ed69907


```Javascript
let text = getVariable('Clipboard');
if (text != null) {
    text = text.replace(/\\r\\n/g, '\r\n')
    text = text.replace(/\\\\/g, '\\')
    text = text.replace(/\\\//g, '/')
    showToast(text)
    setVariable('Clipboard', text)
} else {
    showToast('null clipboard value')
}
```

**Comment by dongbao66** [comment]
> 再帮我试一下吧，看一下能否上传成功，以及提示什么，粘贴的代码以这里的为准
> 
>  Screenrecorder-2024-04-13-18-23-02-883.mp4 
> ```js
> let text = getVariable('Clipboard');
> if (text != null) {
>     text = text.replace(/\\r\\n/g, '\r\n')
>     text = text.replace(/\\\\/g, '\\')
>     text = text.replace(/\\\//g, '/')
>     showToast(text)
>     setVariable('Clipboard', text)
> } else {
>     showToast('null clipboard value')
> }
> ```

把上面的代码放到脚本编写里面后，在磁贴点上传，由于看视频也把//上传成功注释了，手机不提示上传成功了，电脑同样还是空白。
但是在手机app里面点上传，电脑可以正常同步获取信息，
还是一样。
你没有遇到这个问题吗？

**Comment by Jeric-X** [comment]
因为我加了新的提示`setVariable('Clipboard', text)`，所以把之前的那个注释了，应该提示的是剪贴板内容，没有可能就是没获取到。我两种触发方式一直都是成功的
把代码换成这个试试呢
```
let text = getClipboardContent()
if (text != null) {
    showToast(text)
    setVariable('Clipboard', text)
} else {
    showToast('null clipboard value')
}
```

**Comment by dongbao66** [comment]
第一次修改代码情况下，如果是提示复制的内容的话，在app内点击，会提示，能上传成功。在磁贴点击什么都不会提示

**Comment by dongbao66** [comment]
> 因为我加了新的提示`setVariable('Clipboard', text)`，所以把之前的那个注释了，应该提示的是剪贴板内容，没有可能就是没获取到。我两种触发方式一直都是成功的 把代码换成这个试试呢
> 
> ```
> let text = getClipboardContent()
> if (text != null) {
>     showToast(text)
>     setVariable('Clipboard', text)
> } else {
>     showToast('null clipboard value')
> }
> ```

换成这个点击磁贴上传，显示
![1](https://github.com/Jeric-X/SyncClipboard/assets/95880227/9bfc4eae-050c-4c8a-9524-4b96cc9247f0)

而在app内点击上传，会显示复制内容，并上传成功

**Comment by Jeric-X** [comment]
是什么WebDAV提供商，坚果云的话短时间次数过多会这样

**Comment by dongbao66** [comment]
自己搭的cloudreve网盘的webdav

**Comment by dongbao66** [comment]
> 是什么WebDAV提供商，坚果云的话短时间次数过多会这样

重试了一下，不过现在不会提示上面错误但是 什么都不会提示

**Comment by Jeric-X** [comment]
我又想到了一个原因，如果大于等于安卓10的话，后台无法获取剪贴板，但是从后台切回前台获取剪贴板还是有一个延时，就像[这个文章](https://blog.csdn.net/weixin_44043817/article/details/108040598)说的，有可能是HTTP Request更新优化了一波启动速度。不知道你懂不懂js，可以自己尝试加一个sleep函数手动延迟1妙后再获得剪贴板，我随手百度是好像没有这种函数，一会有点事暂时看不了，之后我再想想办法验证一下是不是这个问题

**Comment by dongbao66** [comment]
不懂代码












栋源
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月13日(周六) 晚上8:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jeric-X/SyncClipboard] 安卓上传电脑显示空白，但提示上传成功（以前好好的更新后不知道怎么了） (Issue #62)




 
我又想到了一个原因，如果大于等于安卓10的话，后台无法获取剪贴板，但是从后台切回前台获取剪贴板还是有一个延时，就像这个文章说的，有可能是HTTP Request更新优化了一波启动速度。不知道你懂不懂js，可以自己尝试加一个sleep函数手动延迟1妙后再获得剪贴板，我随手百度是好像没有这种函数，一会有点事暂时看不了，之后我再想想办法验证一下是不是这个问题

**Comment by dongbao66** [comment]
找到解决办法了。
原因是由于我开启了最新版http的实验性功能导致的。
![Screenshot_2024-04-13-21-02-59-58_2336fb421d5c0b1cb70534a33f41c259](https://github.com/Jeric-X/SyncClipboard/assets/95880227/f29d0d3a-b3b7-41be-beb2-ea85643c2048)

切换成默认就好了😂

**Comment by Jeric-X** [comment]
你tm，行

**Comment by dongbao66** [comment]
爱你😘老哥

**Comment by ningcol** [comment]
我是第一次下载安装，使用的是安卓最新版本的快捷指令http，和mac客户端，docker安装的独立服务端

<img width="834" alt="image" src="https://github.com/Jeric-X/SyncClipboard/assets/9313847/7e4e247d-b7ce-4aec-9b72-595d411fc3a9">

**Comment by Jeric-X** [comment]
@ningcol 
那就先试这个https://github.com/Jeric-X/SyncClipboard/issues/62#issuecomment-2053593342
然后试这个https://github.com/Jeric-X/SyncClipboard/issues/62#issuecomment-2053618818
