### ISSUE TITLE
自动上传验证码无法运行

### ISSUE THREAD

**Issue by Goojoe** [Jeric-X/SyncClipboard#63]
![Screenshot_2024-04-23-23-04-43-448_org autojs autoxjs v6](https://github.com/Jeric-X/SyncClipboard/assets/78355492/dd35eb03-b383-4fab-b215-7a0f0e0cb9ac)

**Comment by Goojoe** [comment]
![IMG_20240424_004834](https://github.com/Jeric-X/SyncClipboard/assets/78355492/ef7f37f6-a8cd-46cc-a48a-5c8bc4ed0635)
确实没打开通知权限，打开通知权限后为上面的图片日志

新建脚本代码稳定运行

**Comment by Jeric-X** [comment]
看起来第49行没做null检查，我之后会提交到github，你可以自己先加上确认还有没有别的问题

**Comment by Goojoe** [comment]
要加上什么代码？

**Comment by Jeric-X** [comment]
看报错提示，调用includes前检查一下是不是null，不是null的话再调用。js语法网上一搜挺多的，不行的话还是等我明天改吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 咕咕乔 ***@***.***&gt;
发送时间: 2024年4月24日 01:16
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] 自动上传验证码无法运行 (Issue #63)

**Comment by Jeric-X** [comment]
改好了

**Comment by Goojoe** [comment]
可以运行，但是并没有上传验证码（没有toast），得我手动复制验证码才行

**Comment by Jeric-X** [comment]
https://github.com/Jeric-X/SyncClipboard/issues/63#issuecomment-2072894244
运行这条评论里的代码，观察收到信息和其他推送时有没有toast

**Comment by Goojoe** [comment]
不能准确识别短信应用的通知，会识别到其他隐藏通知

**Comment by Goojoe** [comment]
并没有，我认为这个不太好用，我的手机ROOT后完全可以使用xposedsms复制验证码。或者使用shortx

**Comment by Jeric-X** [comment]
不如由你来写一下，不管是自用还是分享出来给其他人使用，参考我的js代码逻辑应该是很简答的
我没有root的安卓设备，在我能力之外或适用范围过于小众的方案我很难适配

**Comment by Jeric-X** [comment]
> 不能准确识别短信应用的通知，会识别到其他隐藏通知

回到本来的问题，不需要的话可以关闭issue
其他APP的通知能识别到吗
另外可以仔细找找，也不是我怀疑你，我的MIUI10设备都有短信读取权限控制

**Comment by Goojoe** [comment]
算了我有root还考虑这个干嘛，你关吧
