### ISSUE TITLE
加密

### ISSUE THREAD

**Issue by Goojoe** [Jeric-X/SyncClipboard#64]
看了一下webdav居然是明文，不加密一下吗
虽然有性能损失，但这是极度隐私的，加密还是很有必要吧

**Comment by Jeric-X** [comment]
加密当然有必要，没有加密这点readme里也有写，当前的情况如果需要在公共网络使用，建议在服务端使用反向代理配置HTTPS

**Comment by Goojoe** [comment]
不，我是说webdav里的 /SyncClipboard.json text是明文的

**Comment by Jeric-X** [comment]
你的意思是你不信任服务器提供商？

**Comment by Goojoe** [comment]
我不信任何的服务器提供商

**Comment by Jeric-X** [comment]
端到端加密在我这里优先级很低
