### ISSUE TITLE
有没有计划搞个配置同步

### ISSUE THREAD

**Issue by patialo** [Jeric-X/SyncClipboard#65]
配置同步我觉得可以搞一个哎，没计划请close

**Comment by Jeric-X** [comment]
是指怎么同步？两个电脑端，一台电脑改配置了另一个电脑就自动改？

**Comment by patialo** [comment]
对的，因为我电脑端很多，经常得手动设置

**Comment by Jeric-X** [comment]
仔细想了想，还得考虑哪些配置同步哪些不同步，每个客户端想同步的配置也不一样，最想同步的服务器相关配置又同步不了，还是不做开发计划了
