### ISSUE TITLE
这个对文件的大小有限制吗

### ISSUE THREAD

**Issue by frankeson** [Jeric-X/SyncClipboard#66]
PC上复制文件，在安卓上用那个HTTP客户端下载，老是提示404，而且是本地服务器，而且有时候提示是 返回内容过多，限制1.0MB

**Comment by Jeric-X** [comment]
PC端有大小设置。
限制1MB是文件内容的展示，你仍可以分享or保存。

**Comment by frankeson** [comment]
谢谢大佬的回复，但是我用http手机客户端，在使用外网alist 服务器上传20来M的文件的时候总是提示超时，是不是还有什么地方要设置吗，这个项目真的很不错

**Comment by Jeric-X** [comment]
`http手机客户端`指的是[HTTP Request Shortcuts](https://github.com/Waboodoo/HTTP-Shortcuts)？每个`HTTP快捷方式`的高级设置里有一个设置项`创建超时`，也就是超时时长，你可以试试

**Comment by frankeson** [comment]
对的就是HTTP Request Shortcuts，我设置了，但还是显示超时，不知道怎么回事，我发现传到alist里的文件，比如原文件有18M，传上去的有7M左右，然后就超时了
