### ISSUE TITLE
公网部署后显示 404

### ISSUE THREAD

**Issue by henryxrl** [Jeric-X/SyncClipboard#70]
我尝试着把 http://ip:5033 通过 Cloudflare Tunnel 反向代理成一个公共 url。然而访问那个 url 的时候确提示 404，No webpage was found for the web address。

请问我该如何正确的反向代理呢？

**Comment by Jeric-X** [comment]
不好意思，我没有使用过Cloudflare Tunnel，我只在Linux使用nginx配置过反向代理
如果在不使用反向代理的情况下能够访问根目录并返回`Server is running.`消息，可能是Cloudflare使用的问题

**Comment by henryxrl** [comment]
嗯嗯，不用 Cloudflare tunnel 就搞定了！感谢
