### ISSUE TITLE
请求加入多个服务端配置功能

### ISSUE THREAD

**Issue by jaychoutzj** [Jeric-X/SyncClipboard#71]
用家里的NAS配置了docker服务端，但是家里只有V6公网，因此在外面使用wifi时通过V4内网穿透使用（外面的wifi基本没V6），用流量时使用V6直连。因此希望能配置多个服务端地址，根据地址排序轮询，这样能充分利用内网资源（如优先使用内网IP）和V6直连资源。

**Comment by Jeric-X** [comment]
这种的感觉有点难做呀，在按优先级排序查询的情况下，优先级高的地址无法连接时可能会卡住较长的时间，反倒导致更慢。桌面端支持真多线程确实可以实现，不过桌面端对这种情况的需求应该不多。移动端可以拷贝多份配置，手动选择最佳的配置，倒也算是能解决问题
我之前涉及内外网的情况是在内网搭了一个dns服务器，并配置到内网路由器中，这样在设备在内网就会解析到内网地址，外网则解析到外网地址。如果还存在某种优先使用IPV6的机制，再加上IPV6的dns解析，就能完美解决你的问题了
