### ISSUE TITLE
Menu Bar 图标颜色不正确

### ISSUE THREAD

**Issue by Sponge-bink** [Jeric-X/SyncClipboard#73]
### 错误描述 | Describe the bug

虽然系统是暗黑模式但是桌面壁纸是浅色，所以 Menu Bar 仍是浅色，导致浅色背景下浅色图标：
<img width="182" alt="image" src="https://github.com/Jeric-X/SyncClipboard/assets/33798984/959ac02b-5c17-4aae-a09d-e4d68c9b2ad9">
深色背景同：

<img width="183" alt="bsygju30 x5c" src="https://github.com/Jeric-X/SyncClipboard/assets/33798984/c726d7cc-deea-434c-a76c-b5d4d4c511d3">

### 复现步骤 | Steps to Reproduce

设置浅色背景，确认 Menu Bar 背景是浅色，切换至暗黑模式。
深色背景同

### 桌面端信息 | Desktop

MacOS 14.5 Synclipboard Version 0.7.0

**Comment by Jeric-X** [comment]
https://github.com/Jeric-X/SyncClipboard/actions/runs/9194656042
