### ISSUE TITLE
AppData 中的檔案似乎不會自動刪除

### ISSUE THREAD

**Issue by ACh-K** [Jeric-X/SyncClipboard#76]
### 错误描述 | Describe the bug

在兩端開啟「Mixed Client Mode」以及在 client 端開啟「Delete server's temporary file automatically」的情況下，
Server 端的 `AppData\Roaming\SyncClipboard\file` 資料夾中依然會囤積檔案（圖一）。
Client 端似乎也有這個問題（圖二），只是檔案不會完全依照當天放（圖三）。

另外即使將兩端的「Log Remain Days」更改為 `1` 之後，
`AppData\Roaming\SyncClipboard\log` 資料夾中的檔案依然會繼續囤積不會自動刪除。

### 复现步骤 | Steps to Reproduce

1. 開啟 SyncClipboard
2. 進行複製剪貼等動作

### 截图 | Screenshots

- 圖一
  <img width="686" alt="uoir2g0d hoa" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/39aef34a-e9ec-42f9-bd24-01d397bf9a71">

- 圖二
  <img width="1032" alt="hdjs3f4b ahl" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/f93653fc-0173-4c9a-8000-b09018f84968">
- 圖三
  <img width="1032" alt="uyi1a5rb 2dm" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/78dee65c-2658-4ae5-991b-bf0d641663ec">

### 桌面端信息 | Desktop

OS: Windows 11 23H2, Synclipboard Version: v2.8.0

### 移动端信息 | Smartphone

OS: macOS 14.5, Synclipboard Version: v0.7.0

### 其他附加信息 | Additional context

不太清楚為什麼在 server 端 `file\[日期]\temp images` 當中會在短時間內充斥著大量重複的複製過的圖片，例如剛才的「圖一」。
<img width="686" alt="chqdstnt 2ai" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/d0d3c59d-f2a9-489d-94e1-6f927859007d">

同時也在猜想這是不是造成 `file` 資料夾本身如此龐大的原因。
<img width="329" alt="f5iao2bc san" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/5149d1f4-0745-420b-81bf-8e4d1fde1250">

這個狀況在 client 端就輕微很多。
<img width="1032" alt="image" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/6ff1721c-8c40-411b-8ece-d15006627493">

**Comment by Jeric-X** [comment]
临时文件无法自动删除的问题由此版本引入，预计今天或明天会发布新版本修复
服务端生成大量图片文件是一直以来的问题，长时间都没被注意，只在混合模式出现，关闭混合模式应该可以暂时规避这个问题，修复时间会稍长一点

**Comment by Jeric-X** [comment]
发布新版本了
另外，我在dev分支尝试修复了服务器产生大量图片文件的问题，如果有兴趣可以提前下载，当然也可能会有更多的问题。这是最近的build，https://github.com/Jeric-X/SyncClipboard/actions/runs/9234495788

**Comment by ACh-K** [comment]
> 临时文件无法自动删除的问题由此版本引入，预计今天或明天会发布新版本修复 服务端生成大量图片文件是一直以来的问题，长时间都没被注意，只在混合模式出现，关闭混合模式应该可以暂时规避这个问题，修复时间会稍长一点

新版本（v2.8.1, v0.7.1）似乎還是不會依照設定（1 天）自動刪除 log 文檔，臨時文件也沒有要自動刪除的跡象🤔

<img width="687" alt="drksqxrm qqf" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/4010d3f1-c06a-4a86-b0a7-3c513a8a229b">
<img width="687" alt="cs5nzjqj zup" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/1ffc6630-e313-4291-932b-f6a1c32d959f">
<img width="1032" alt="image" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/634c4e74-7fdc-4655-9ec5-1c48acdc6975">
<img width="1032" alt="image" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/cb6b83fb-fdbb-48a8-90de-b6a75503a21c">

**Comment by Jeric-X** [comment]
自动删除file中文件可能会延迟一天，但不会超过两天，并且会默认保留前一天的记录，总之就是最多会同时存在3天的日期文件夹，log保留日期设置成1的话同理最多有3天记录，目前是这样的，麻烦再观察一下吧。
话说你的log文件怎么这么大，我的每天就十几MB

**Comment by ACh-K** [comment]
我這邊的 log 光是一秒內就會留下好幾十行甚至百行的紀錄，比如 `[2024/05/27 02:53:58]` 的紀錄就有這麼多：

<img width="752" alt="hbuwv4v5 21p" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/0672530f-76ba-4fe6-bbb3-bec87080578a">

其實我以為 log 文件很大是這個軟體正常的現象（

**Comment by Jeric-X** [comment]
是不是你的查询间隔设置成0了？这样cpu和电池的压力有点大呀，可能设置成1比较好？我可能在未来把这个配置限制成1是最小值了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ACh ***@***.***&gt;
发送时间: 2024年5月27日 02:58
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] AppData 中的檔案似乎不會自動刪除 (Issue #76)





 
我這邊的 log 光是一秒內就會留下好幾十行甚至百行的紀錄，比如 [2024/05/27 02:53:58] 的紀錄就有這麼多：
 hbuwv4v5.21p.png (view on web) 
其實我以為 log 文件很大是這個軟體正常的現象（

**Comment by ACh-K** [comment]
哦哦哦原來那個是指 log 紀錄的間隔，我一開始以為是複製檔案的間隔所以就設成 0 了 ww 非常感謝提醒🙏

**Comment by Jeric-X** [comment]
不是不是，是指查询服务器剪贴板是否有更新的间隔，每次查询都会记录log，而且设置成0对于服务端来说甚至有点像DoS攻击，最好还是不要设置成0啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ACh ***@***.***&gt;
发送时间: 2024年5月27日 03:16
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] AppData 中的檔案似乎不會自動刪除 (Issue #76)





 
哦哦哦原來那個是指 log 紀錄的間隔，我一開始以為是複製檔案的間隔所以就設成 0 了 ww 非常感謝提醒🙏

**Comment by ACh-K** [comment]
> 哦哦哦原來那個是指 log 紀錄的間隔，我一開始以為是複製檔案的間隔所以就設成 0 了 ww 非常感謝提醒🙏

剛剛試了幾次之後發現我一開始以為的應該沒想錯（

我一開始會設成 0 主要是想要達成「有一個裝置進行複製就能立即在另一個裝置響應」那種不受時間限制的感覺，但我不知道這對電腦的負擔會那麼大 w（短時間內大量查詢剪貼板是否有更新）

說到這裡，我在想有沒有辦法不用隨時檢查剪貼板有沒有更新，等有按下複製鍵再確認剪貼板的內容之類的？

**Comment by Jeric-X** [comment]
如果服务端和客户端能都能主动发起通讯的话是可以做到的，有变化的设备主动通知其他设备即可。但目前为了兼容WebDav（其实是早期服务端只支持webdav，为了代码的一致与简单），只能由客户端主动查询，服务端被动返回。
我可能会想要先进行下边的简单方案：
用毫秒为单位进行设置，这样即使是300ms的延迟也不会太大，资源的消耗也就还好，以后还可能对log进行分级，少输出些无用信息


真·双向通信的开发是有想过的，但是没什么具体计划

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ACh ***@***.***&gt;
发送时间: 2024年5月27日 03:39
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] AppData 中的檔案似乎不會自動刪除 (Issue #76)





  
哦哦哦原來那個是指 log 紀錄的間隔，我一開始以為是複製檔案的間隔所以就設成 0 了 ww 非常感謝提醒🙏
  
剛剛試了幾次之後發現我一開始以為的應該沒想錯（
 
我一開始會設成 0 主要是想要達成「有一個裝置進行複製就能立即在另一個裝置響應」那種不受時間限制的感覺，但我不知道這對電腦的負擔會那麼大 w（短時間內大量查詢剪貼板是否有更新）
 
說到這裡，我在想有沒有辦法不用隨時檢查剪貼板有沒有更新，等有按下複製鍵再確認剪貼板的內容之類的？

**Comment by ACh-K** [comment]
自動刪除的部分應該是沒問題了👍
