### ISSUE TITLE
macOS 選單列圖像被切邊

### ISSUE THREAD

**Issue by ACh-K** [Jeric-X/SyncClipboard#78]
### 错误描述 | Describe the bug

從截圖中可以看到圖案的這幾種狀態當中，右手邊都有點被裁切的跡象。

### 复现步骤 | Steps to Reproduce

1. 開啟 SyncClipboard

### 截图 | Screenshots

<img width="176" alt="image" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/d46dba14-9c20-4981-ac7e-da5aa338b366">
<img width="176" alt="image" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/28879120-c168-49a9-8951-8391052ee209">
<img width="176" alt="image" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/9eb32a9c-ce94-474d-9ec4-afd5c8b62ee7">
<img width="176" alt="blp0qr3a wmb" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/91898a63-eb15-44b9-a3ac-e8917e99c30c">

### 桌面端信息 | Desktop

OS: Windows 11 23H2, Synclipboard Version: v2.8.1

### 移动端信息 | Smartphone

OS: macOS 14.5, Synclipboard Version: v0.7.1

### 其他附加信息 | Additional context

不算是多嚴重的 bug 但還是想提一下 w

**Comment by Jeric-X** [comment]
仔细一看，确实有这个问题 w

**Comment by ACh-K** [comment]
在未啟動狀態下的圖像好像沒改到 w

https://github.com/Jeric-X/SyncClipboard/assets/98224334/f8268ad8-3792-487b-bab5-58b10684ad3a

**Comment by Jeric-X** [comment]
更新了0.7.3

**Comment by ACh-K** [comment]
> 更新了0.7.3

似乎是沒有問題了👍
