### ISSUE TITLE
快捷指令自动版本下载图片后无法显示，点击通知后跳到快捷指令页面了

### ISSUE THREAD

**Issue by patialo** [Jeric-X/SyncClipboard#79]
### 错误描述 | Describe the bug

ios快捷指令自动版本下载图片后无法显示，点击通知后跳到快捷指令页面，相当于无法保存

### 复现步骤 | Steps to Reproduce

启动自动同步后，电脑上复制一张图片，在ipad端只有通知显示，无法保存

### 桌面端信息 | Desktop

windows10

### 移动端信息 | Smartphone

ipadpro2020

**Comment by Jeric-X** [comment]
只能去支持粘贴图片的地方直接粘贴，没有“点击通知选择是否保存”的功能，要不就无条件保存所有图片，如果你希望的话我可以加一个开关控制是否保存所有图片到相册

**Comment by patialo** [comment]
> 只能去支持粘贴图片的地方直接粘贴，没有“点击通知选择是否保存”的功能，要不就无条件保存所有图片，如果你希望的话我可以加一个开关控制是否保存所有图片到相册

能像手动同步那样跳出来一个模态框吗

**Comment by Jeric-X** [comment]
可以，你自己在快捷指令里第二个圈的地方加一个圈里的东西就行，可以通过第一个圈的内容找位置，不过也是所有的非文字都会弹出，并且卡住整个流程

![IMG_5768](https://github.com/Jeric-X/SyncClipboard/assets/10058586/48c8cc99-d47e-4ec2-8fb7-e18d43da4ce1)

**Comment by patialo** [comment]
这样的话我还是选择图片用手动接收一下，两个快捷指令都用
