### ISSUE TITLE
请求docker部署支持arm64架构

### ISSUE THREAD

**Issue by labulac** [Jeric-X/SyncClipboard#81]
### 描述你想添加的功能 | Describe the feature you'd like

docker hub中好像只有amd的，请求支持arm64

### 描述你正在使用的替代方案 | Describe alternatives you are using

暂无

**Comment by Jeric-X** [comment]
可以帮我试一下`jericx/syncclipboard-server:ci`这个tag下的arm64版能正常运行吗

**Comment by labulac** [comment]
> 可以帮我试一下`jericx/syncclipboard-server:ci`这个tag下的arm64版能正常运行吗

能跑起来，访问5033能看到server is running。刚用这个项目，还在摸索。

**Comment by Jeric-X** [comment]
latest标签里已经支持arm64了
