### ISSUE TITLE
增加上传成功通知

### ISSUE THREAD

**Issue by Wrandz** [Jeric-X/SyncClipboard#82]
### 描述你想添加的功能 | Describe the feature you'd like

我使用Syncclipboard同步台式机，win笔记本，macbook和iPhone，ipad之间的剪切板，非常好用。由于我首先并不是所有的复制粘贴都想同步，其次也不想这么多台设备一直不停地轮询vps，所以我关闭了服务器同步，通过快捷键来上传和下载我想同步的内容。

当下载时，剪切板更新，会有更新；当我上传时，通过快捷键，没有任何成功或失败的通知。

希望增加一个通知，以使我确信，上传已经成功。

### 描述你正在使用的替代方案 | Describe alternatives you are using

目前没有替代方案。

**Comment by Jeric-X** [comment]
可以添加
不过上传失败了应该是有错误提示的，上传过程中托盘栏图标也是有动画效果的，上传成功确实没提示

**Comment by Jeric-X** [comment]
好脑洞，目前同步文字或小文件可能就只是闪一下（甚至有一种是bug导致闪烁的错觉），我可能会延长一下动画播放时间，锦上添花的就是你说的做一个更有特点的动画，我可能需要一个美术朋友帮忙设计一下

**Comment by Jeric-X** [comment]
Windows v2.8.3 添加了选项，可以在手动同步后发送通知
