### ISSUE TITLE
iOS 截图无法成功上传

### ISSUE THREAD

**Issue by huaxianyan** [Jeric-X/SyncClipboard#84]
### 错误描述 | Describe the bug

我使用 iOS 设备分享一张照片到快捷指令，但是发现其他设备无法正常同步，使用 iOS 直接从云端下载剪贴板发现是一个 0 KB 的图片文件

### 复现步骤 | Steps to Reproduce

打开「照片」- 选择一张图片 - 分享 - 选择 「Clipboard EX」

### 截图 | Screenshots

![j0rs5x5k 5zd](https://github.com/Jeric-X/SyncClipboard/assets/19589248/e624ecf5-e314-49e8-b9c7-cbe14f8816de)

### 桌面端信息 | Desktop

Windows 10 22H2, Synclipboard Version: v2.8.2

### 移动端信息 | Smartphone

iOS 17.5 快捷指令

**Comment by Jeric-X** [comment]
1、服务端是什么
2、能在服务器中看到上传的的图片吗
可以先只回答1

**Comment by huaxianyan** [comment]
1. 服务端是 Docker 最新版本镜像
2. 只映射出来 setting 文件，需要告诉我图片放在容器里什么位置

**Comment by Jeric-X** [comment]
文件存放在容器内的/app/server/file/目录里中，当前剪贴板信息存放在/app/server/SyncClipboard.json

**Comment by huaxianyan** [comment]
看不见
![yakogkg3 mfj](https://github.com/Jeric-X/SyncClipboard/assets/19589248/7327dc24-ddb8-4850-ab52-26044a39688f)

**Comment by Jeric-X** [comment]
ios端快捷指令没有任何的报错吗？
退出所有客户端，只用快捷指令上传一次，再看看容器内是否有文件
