### ISSUE TITLE
Windows11 没有通知窗口

### ISSUE THREAD

**Issue by Jeric-X** [Jeric-X/SyncClipboard#85]
### Discussed in https://github.com/Jeric-X/SyncClipboard/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **OxygenLost** June  4, 2024</sup>
是我哪里配置有问题吗
{
  "ServerService": {
    "SwitchOn": false,
    "Port": 5033,
    "UserName": "admin",
    "Password": "admin",
    "ClientMixedMode": false
  },
  "SyncService": {
///
///
///
    "SyncSwitchOn": true,
    "PullSwitchOn": true,
    "PushSwitchOn": true,
    "UseLocalServer": false,
    "DeletePreviousFilesOnPush": true,
    "NotifyOnDownloaded": true,
    "TrustInsecureCertificate": false,
    "MaxFileByte": 20971520,
    "IntervalTime": 1,
    "RetryTimes": 3,
    "TimeOut": 100
  },
  "Program": {
    "Proxy": "",
    "DeleteTempFilesOnStartUp": true,
    "LogRemainDays": 8,
    "CheckUpdateOnStartUp": true,
    "CheckUpdateForBeta": false,
    "Language": "",
    "Font": "",
    "HideWindowOnStartup": true,
    "DiagnoseMode": false,
    "DiagnosePageAutoRefresh": false,
    "Theme": ""
  }
}</div>

**Comment by Jeric-X** [comment]
@OxygenLost 
麻烦你上传一下log吧，右键托盘图标->打开应用数据文件夹->log

**Comment by OxygenLost** [comment]
[202406041.txt](https://github.com/user-attachments/files/15559278/202406041.txt)
我的两台win11 电脑上都没有通知

**Comment by Jeric-X** [comment]
我想确认下同步的功能有成功吗，是不是也没成功，从log观测的现象是每次在修改本地剪贴板的时候直接异常了，所以没有发送通知

**Comment by OxygenLost** [comment]
事实上同步是成功的。我是 ios 上传文字 电脑粘贴。是不是跟我还有微信输入法有关系？我也开着微信输入法的同步

JericX ***@***.***>于2024年6月4日 周二22:38写道：

**Comment by Jeric-X** [comment]
肯定要排除其他因素的影响

**Comment by OxygenLost** [comment]
通知的逻辑是什么样的呢 是写入剪切板之后通知呢还是从服务器获取到消息就通知？

JericX ***@***.***>于2024年6月5日 周三10:36写道：

**Comment by Jeric-X** [comment]
写入本地剪贴板成功后会通知

**Comment by Jeric-X** [comment]
关闭issue了，如果仍需要帮助可以重新打开
