### ISSUE TITLE
win弹窗报错停不下来

### ISSUE THREAD

**Issue by Wrandz** [Jeric-X/SyncClipboard#87]
### 错误描述 | Describe the bug

iPhone上传的图片，win下载失败（目前不知道哪个环节失败了，如果有log可以查就好了）。
然后右下角就开始疯狂弹窗。
![Snipaste_2024-06-07_10-25-55](https://github.com/Jeric-X/SyncClipboard/assets/70056470/4c5a66f3-cd2a-4d9e-9fa2-6c23d9af8d3b)
![Snipaste_2024-06-07_10-22-47](https://github.com/Jeric-X/SyncClipboard/assets/70056470/084a75d4-e8e1-464d-bd96-b9c1b1abd171)
![Snipaste_2024-06-07_10-22-28](https://github.com/Jeric-X/SyncClipboard/assets/70056470/13ad34d2-089c-4ddb-ba9f-f272cb104bf6)

### 复现步骤 | Steps to Reproduce

如上所述

### 桌面端信息 | Desktop

OS: [Windows 11 23H2], Synclipboard Version: [2.8.2]

### 移动端信息 | Smartphone

Device:[iPhone12], Tool:[捷径]

**Comment by Jeric-X** [comment]
是iOS端没有把图片上传上去，电脑到手机传输图片有问题吗

**Comment by Wrandz** [comment]
电脑传到手机上没有遇到问题，我录个屏幕给你看看，这个错误几乎100%在我这里复现。

**Comment by Wrandz** [comment]
手机录屏
https://drive.google.com/file/d/1LQQ7FxgpQnd0NgNbCI9FGnYrDi4Tc4uN/view?usp=sharing

**Comment by Wrandz** [comment]
电脑录屏
https://drive.google.com/file/d/1Lfn5JC97sS72pl6H1zZFG_egWJ6xUxo6/view?usp=sharing

**Comment by Wrandz** [comment]
可以看到电脑上，弹窗没完没了，停不下来

**Comment by Jeric-X** [comment]
在分享菜单直接分享试试呢，可以编辑添加到这里
![IMG_5783](https://github.com/Jeric-X/SyncClipboard/assets/10058586/c69ebad8-6c6d-4922-be83-7c026776370d)

**Comment by Wrandz** [comment]
之前没注意到分享菜单里面有一个Clipboard EX，我刚才试了一下，这是新的录屏，还是不行。

**Comment by Wrandz** [comment]
iPhone12录屏2
https://drive.google.com/file/d/1wGR4CmeM5T3NQrEuif1jjJPiRylSvJZ1/view?usp=sharing

**Comment by Jeric-X** [comment]
好吧，我回头再仔细看一下吧，这两天出差可能会拖一会

------------------ 原始邮件 ------------------
发件人: Wrandz ***@***.***&gt;
发送时间: 2024年6月7日 12:22
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] win弹窗报错停不下来 (Issue #87)





 
之前没注意到分享菜单里面有一个Clipboard EX，我刚才试了一下，这是新的录屏，还是不行。

**Comment by Wrandz** [comment]
win11录屏2
https://drive.google.com/file/d/15-SuhGq1xW9faoEx0B3QlACKPeDomIpo/view?usp=sharing

**Comment by Wrandz** [comment]
> 好吧，我回头再仔细看一下吧，这两天出差可能会拖一会
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Wrandz ***@***.***&gt; 发送时间: 2024年6月7日 12:22 收件人: Jeric-X/SyncClipboard ***@***.***&gt; 抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [Jeric-X/SyncClipboard] win弹窗报错停不下来 (Issue #87) 之前没注意到分享菜单里面有一个Clipboard EX，我刚才试了一下，这是新的录屏，还是不行。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢，感谢！

**Comment by Wrandz** [comment]
刚才偶然间发现，对于一些很小的截图图片jpg，手机上传，电脑下载是没问题的。只有自己手机拍照的照片，可能比较大，统统都失败了。不过失败不要紧，要紧的是，一旦失败，就会不停地弹窗。
我会随时在这里报告新的发现
![微信图片_20240607144332](https://github.com/Jeric-X/SyncClipboard/assets/70056470/0374730f-ae85-4942-b0db-8b77ad005898)

**Comment by Jeric-X** [comment]
你不会也是服务器限制附件大小了吧，之前有个issue也是这样。无限报错这个是得改一下


------------------ 原始邮件 ------------------
发件人: Wrandz ***@***.***&gt;
发送时间: 2024年6月7日 14:46
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] win弹窗报错停不下来 (Issue #87)





 
刚才偶然间发现，对于一些很小的截图图片jpg，手机上传，电脑下载是没问题的。只有自己手机拍照的照片，可能比较大，统统都失败了。不过失败不要紧，要紧的是，一旦失败，就会不停地弹窗。
 我会随时在这里报告新的发现
 _20240607144332.jpg (view on web)

**Comment by Jeric-X** [comment]
你用的是什么服务器

**Comment by Wrandz** [comment]
> 你不会也是服务器限制附件大小了吧，之前有个issue也是这样。无限报错这个是得改一下

一句话点醒梦中人👍我用的nginx反代的，忘记设置client_max_body_size了。我刚才在server中添加了一行
```
client_max_body_size  1024m;
```
就好了。

**Comment by Wrandz** [comment]
> 你用的是什么服务器

vps用的docer compose搭建的

**Comment by Jeric-X** [comment]
看来这个也是经典问题了，以后我也会优先往这个方向排查了


------------------ 原始邮件 ------------------
发件人: Wrandz ***@***.***&gt;
发送时间: 2024年6月7日 23:09
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: JericX ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] win弹窗报错停不下来 (Issue #87)





  
你不会也是服务器限制附件大小了吧，之前有个issue也是这样。无限报错这个是得改一下
  
一句话点醒梦中人👍我用的nginx反代的，忘记设置client_max_body_size了。我刚才在server中添加了一行
 client_max_body_size  1024m;  
就好了。

**Comment by Jeric-X** [comment]
Windows v2.8.3 Desktop v0.7.4  修复了无限报错
