### ISSUE TITLE
macOS 截圖複製問題

### ISSUE THREAD

**Issue by ACh-K** [Jeric-X/SyncClipboard#88]
### 错误描述 | Describe the bug

利用 macOS 內建的截圖功能按住 Control 鍵進行第二次截圖之後，在 Windows 貼上的依然會是第一次截圖。

Windows 內建的剪取工具則沒有這個問題。

### 复现步骤 | Steps to Reproduce

1. 在 macOS 中利用內建功能按住 Control 鍵截圖（將截圖複製到剪貼板）
2. 在 macOS 中利用內建功能再次按住 Control 鍵截圖
3. 在 Windows 貼上圖片

### 截图 | Screenshots

從影片可以看到只有第一次的截圖出現在 `temp images` 資料夾中。

https://github.com/Jeric-X/SyncClipboard/assets/98224334/0e3651b4-35ef-4a49-82dd-2eeaa02bf7ae

### 桌面端信息 | Desktop

OS: Windows 11 23H2, Synclipboard Version: v2.8.2

### 移动端信息 | Smartphone

OS: macOS 14.5, Synclipboard Version: v0.7.3

**Comment by Jeric-X** [comment]
macOS 0.7.4 修复了这个问题
