### ISSUE TITLE
桌面端，短时间内多次复制文本，会出现新复制的文本被之前复制的文本覆盖的情况

### ISSUE THREAD

**Issue by TCOTC** [Jeric-X/SyncClipboard#91]
### 错误描述 | Describe the bug

桌面端，短时间内多次复制文本，会出现新复制的文本被之前复制的文本覆盖的情况（也许是传上 WebDAV 之后又被拉取回来了？）

### 复现步骤 | Steps to Reproduce

桌面端，短时间内多次复制文本

### 截图 | Screenshots

![image](https://github.com/Jeric-X/SyncClipboard/assets/78434827/3bee81fa-0911-4c61-ba67-ea18396591c0)

### 桌面端信息 | Desktop

Windows 10 22H2 v2.8.2

**Comment by Jeric-X** [comment]
Windows v2.8.3 修复了这个问题

**Comment by TCOTC** [comment]
试了一下，应该没有这个问题了
