### ISSUE TITLE
MacOS 下无限循环同步图片

### ISSUE THREAD

**Issue by sautvaste** [Jeric-X/SyncClipboard#94]
### 错误描述 | Describe the bug

安卓分享图片，Mac 端无限同步，且文件一直被替换

### 复现步骤 | Steps to Reproduce

1. Docker 部署，宿主机系统是 Manjaro Linux
2. Android 使用 HTTP Request Shortcuts 快捷分享图片
3. Mac 客户端打开同步通知，同步图片

### 截图 | Screenshots

![SCR-20240620-v9z](https://github.com/Jeric-X/SyncClipboard/assets/50456958/9ccf03c8-2bf7-43b6-b76f-a07449eb8aa0)
![SCR-20240620-vll](https://github.com/Jeric-X/SyncClipboard/assets/50456958/2dea24e8-e501-4e9d-abaf-9baa038ee6d8)

### 桌面端信息 | Desktop

MacOS 14.2.1

### 移动端信息 | Smartphone

Redmi K40 HyperOS 1.0.3.0

### 其他附加信息 | Additional context

Docker image: jericx/syncclipboard-server:latest

**Comment by sautvaste** [comment]
> 刚刚发布了新版本，试一试

确认 0.7.4 已修复，来得早不如来得巧，谢谢！

**Comment by dumengzhao** [comment]
我的版本是2.9.0，为什也有这个问题
