### ISSUE TITLE
`ios 手动快捷指令`和`windows的clip`在webdav服务器中建立的文件不在同一位置

### ISSUE THREAD

**Issue by robin758** [Jeric-X/SyncClipboard#96]
### 错误描述 | Describe the bug

![w2ywjxk4 qhx](https://github.com/Jeric-X/SyncClipboard/assets/83524955/cf15666d-0e04-40f8-ad85-d2f0551cfa11)

如图所示, ios上传的文本在下面的json里面, windows上传的文本则在上面文件夹里面的json里面, 导致这两个端文本不能同步, 但是windows和安卓是没有问题的

### 复现步骤 | Steps to Reproduce

同上

### 服务端信息 | Server

infinicloud

**Comment by Jeric-X** [comment]
是ios的配置多写了一个文件夹吧


------------------ 原始邮件 ------------------
发件人: robin758 ***@***.***&gt;
发送时间: 2024年6月25日 18:32
收件人: Jeric-X/SyncClipboard ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Jeric-X/SyncClipboard] `ios 手动快捷指令`和`windows的clip`在webdav服务器中建立的文件不在同一位置 (Issue #96)





 
错误描述 | Describe the bug
 
w2ywjxk4.qhx.png (view on web)
 
如图所示, ios上传的文本在下面的json里面, windows上传的文件则在上面文件夹里面的json里面
 
复现步骤 | Steps to Reproduce
 
同上
 
截图 | Screenshots
 
No response
 
服务端信息 | Server
 
infinicloud
 
桌面端信息 | Desktop
 
No response
 
移动端信息 | Smartphone
 
No response
 
其他附加信息 | Additional context
 
No response

**Comment by robin758** [comment]
我没修改过，用的是 readme 里面的手动快捷指令

![2d5ca5kn mkq](https://github.com/Jeric-X/SyncClipboard/assets/83524955/47620ec1-5258-4a67-9c6d-2f98e5411a1a)
