### ISSUE TITLE
docker-compose 部署成功后,报错,无法同步

### ISSUE THREAD

**Issue by wsry888** [Jeric-X/SyncClipboard#99]
### 错误描述 | Describe the bug

info: SyncClipboard.Server.BasicAuthenticationHandler[7]
      BasicAuthentication was not authenticated. Failure message: Invalid Authorization Header
info: SyncClipboard.Server.BasicAuthenticationHandler[12]
      AuthenticationScheme: BasicAuthentication was challenged.

### 复现步骤 | Steps to Reproduce

无法同步剪贴板

### 服务端信息 | Server

docker

**Comment by Jeric-X** [comment]
账号密码错误

**Comment by wsry888** [comment]
我都用默认的admin,服务端是能正常跑的,客户端连接不上服务端.
<img width="388" alt="e202nsdz wbe" src="https://github.com/Jeric-X/SyncClipboard/assets/21898282/6839c2e5-0827-4985-bcd4-6e2f591fc85f">
<img width="591" alt="1nj3zxh3 nuh" src="https://github.com/Jeric-X/SyncClipboard/assets/21898282/1bf2a3ce-6ddd-4dd6-a76d-ee2b9ceb7b49">

**Comment by Jeric-X** [comment]
多试几种别的客户端，然后客户端的报错也发一下
